// GENERATED FILE — do not hand-edit.
// Regenerate via `python3 tools/generate_banner_catalog.py` from
// Honeycomb_Localization.xlsx (BannerFlavorText sheet).

package com.leah.honeycomb

import kotlinx.serialization.Serializable

enum class BannerId {
    RuleSpecificNectarExchangeSwapsAwayThePlayers5StarCard,
    RuleSpecificNectarExchangeTradesThePlayersWorstCardForThe,
    RuleSpecificRouletteRollsZeroExtraRules,
    LoadingGameLoadsOnMay20thWorldBeeDay,
    LoadingGameLoadsOnNewYearsDayJan1,
    LoadingGameLoadsOnHalloweenOct31,
    LoadingGameLoadsOnValentinesDayFeb14,
    LoadingFirstLaunchAfterPlayingForOneYear,
    LoadingPlayingOnAprilFoolsDayApr1,
    LoadingMatchStartsBetween1200AmAnd500AmLocalTime,
    LoadingMatchStartsBetween500AmAnd800AmLocalTime,
    LoadingMatchStartsBetween900PmAndMidnightLocalTime,
    LoadingMatchStartsWithinAMinuteOfLocalNoon,
    LoadingMatchStartsBetween800AmAnd1200PmLocalTime,
    LoadingMatchStartsBetween1200PmAnd200PmLocalTime,
    LoadingMatchStartsBetween200PmAnd500PmLocalTime,
    LoadingMatchStartsBetween500PmAnd900PmLocalTime,
    LoadingOnGameLoad,
    IdleActionNoActionTakenForOneMinute,
    Gameplay3HintsUsedInOneMatch,
    GameplayUndoUsedImmediatelyAfterAPlacement,
    GameplayPlayerWinsAMatchWith4RulesActiveAtOnce,
    GameplayOpponentIsWinningByTwoCardsAndIsAboutToPlaceThe,
    GameplayPlayerFlips3CardsInASingleTurn,
    GameplayOpponentFlips3OfThePlayersCardsInASingleTurnNotA,
    GameplayComboX4OrHigher,
    GameplayPlayerHasOnly2CardsOnTheBoardVsOpponents6Few,
    GameplayAPlacedCardCapturesOnAll4SidesAtOnce,
    Gameplay3RematchWinsInARowAgainstTheSameOpponent,
    Gameplay3RematchLossesInARowAgainstTheSameOpponent,
    GameplayA1StarCardCaptures3CardsInOneMove,
    GameplayA1StarCardCapturesA5StarCardRarityMismatch,
    GameplayPlayerUsesUndoThinksAboutItAndThenMakesTheExact,
    GameplayPlayerPlaysAgainstTheSameAiDifficulty5TimesInARow,
    GameplayPlayerWinsByTheMaximumPossibleMargin,
    MilestonesFirstLaunchEver,
    MilestonesPlayerReaches10TotalWins,
    MilestonesPlayerReaches100TotalWins,
    MilestonesPlayerReaches1000TotalWins,
    RuleSpecificFallenAceTriggersA1CapturesA10,
    RuleSpecificPollinationPushesACardsModifierTo3OrHigher,
    RuleSpecificSmokedOutDropsACardsEffectiveStatTo1,
    RuleSpecificAPlayerTriggersAPlusComboTheMathMatchesPerfectly,
    RuleSpecificPlayerWinsFlawlessOpponentScore0,
    RuleSpecificPlayerLosesFlawless0Captures,
    RuleSpecificRouletteRollsPollination,
    RuleSpecificRouletteRollsSmokedOut,
    RuleSpecificRouletteRollsMathBee,
    RuleSpecificRouletteRollsInversion,
    RuleSpecificRouletteRollsClearSkies,
    RuleSpecificRouletteRollsScoutingParty,
    RuleSpecificRouletteRollsFrenzy,
    RuleSpecificRouletteRollsSymmetry,
    RuleSpecificRouletteRollsNectarExchange,
    RuleSpecificRouletteRollsHierarchy,
    LoadingGameLoadsOnEarthDayApr22,
    LoadingGameLoadsOnNationalHoneyDayAug15,
    LoadingGameLoadsOnPiDayMar14,
    LoadingGameLoadsOnNewYearsEveDec31,
    LoadingGameLoadsOnChristmasDec25,
    LoadingGameLoadsOnHoli,
    LoadingGameLoadsOnRoshHashanah,
    LoadingGameLoadsOnDiwali,
    LoadingGameLoadsOnEidAlFitr,
    LoadingGameLoadsOnHanukkah,
    GameplayPlayerRunsOutOfCreditsVideoPokerBlackjack,
}

object BannerIdExtensions {
    private val ById = mapOf(
        "rule_specific_nectar_exchange_swaps_away_the_players_5_star_card" to BannerId.RuleSpecificNectarExchangeSwapsAwayThePlayers5StarCard,
        "rule_specific_nectar_exchange_trades_the_players_worst_card_for_the" to BannerId.RuleSpecificNectarExchangeTradesThePlayersWorstCardForThe,
        "rule_specific_roulette_rolls_zero_extra_rules" to BannerId.RuleSpecificRouletteRollsZeroExtraRules,
        "loading_game_loads_on_may_20th_world_bee_day" to BannerId.LoadingGameLoadsOnMay20thWorldBeeDay,
        "loading_game_loads_on_new_years_day_jan_1" to BannerId.LoadingGameLoadsOnNewYearsDayJan1,
        "loading_game_loads_on_halloween_oct_31" to BannerId.LoadingGameLoadsOnHalloweenOct31,
        "loading_game_loads_on_valentines_day_feb_14" to BannerId.LoadingGameLoadsOnValentinesDayFeb14,
        "loading_first_launch_after_playing_for_one_year" to BannerId.LoadingFirstLaunchAfterPlayingForOneYear,
        "loading_playing_on_april_fools_day_apr_1" to BannerId.LoadingPlayingOnAprilFoolsDayApr1,
        "loading_match_starts_between_12_00_am_and_5_00_am_local_time" to BannerId.LoadingMatchStartsBetween1200AmAnd500AmLocalTime,
        "loading_match_starts_between_5_00_am_and_8_00_am_local_time" to BannerId.LoadingMatchStartsBetween500AmAnd800AmLocalTime,
        "loading_match_starts_between_9_00_pm_and_midnight_local_time" to BannerId.LoadingMatchStartsBetween900PmAndMidnightLocalTime,
        "loading_match_starts_within_a_minute_of_local_noon" to BannerId.LoadingMatchStartsWithinAMinuteOfLocalNoon,
        "loading_match_starts_between_8_00_am_and_12_00_pm_local_time" to BannerId.LoadingMatchStartsBetween800AmAnd1200PmLocalTime,
        "loading_match_starts_between_12_00_pm_and_2_00_pm_local_time" to BannerId.LoadingMatchStartsBetween1200PmAnd200PmLocalTime,
        "loading_match_starts_between_2_00_pm_and_5_00_pm_local_time" to BannerId.LoadingMatchStartsBetween200PmAnd500PmLocalTime,
        "loading_match_starts_between_5_00_pm_and_9_00_pm_local_time" to BannerId.LoadingMatchStartsBetween500PmAnd900PmLocalTime,
        "loading_on_game_load" to BannerId.LoadingOnGameLoad,
        "idle_action_no_action_taken_for_one_minute" to BannerId.IdleActionNoActionTakenForOneMinute,
        "gameplay_3_hints_used_in_one_match" to BannerId.Gameplay3HintsUsedInOneMatch,
        "gameplay_undo_used_immediately_after_a_placement" to BannerId.GameplayUndoUsedImmediatelyAfterAPlacement,
        "gameplay_player_wins_a_match_with_4_rules_active_at_once" to BannerId.GameplayPlayerWinsAMatchWith4RulesActiveAtOnce,
        "gameplay_opponent_is_winning_by_two_cards_and_is_about_to_place_the" to BannerId.GameplayOpponentIsWinningByTwoCardsAndIsAboutToPlaceThe,
        "gameplay_player_flips_3_cards_in_a_single_turn" to BannerId.GameplayPlayerFlips3CardsInASingleTurn,
        "gameplay_opponent_flips_3_of_the_players_cards_in_a_single_turn_not_a" to BannerId.GameplayOpponentFlips3OfThePlayersCardsInASingleTurnNotA,
        "gameplay_combo_x4_or_higher" to BannerId.GameplayComboX4OrHigher,
        "gameplay_player_has_only_2_cards_on_the_board_vs_opponents_6_few" to BannerId.GameplayPlayerHasOnly2CardsOnTheBoardVsOpponents6Few,
        "gameplay_a_placed_card_captures_on_all_4_sides_at_once" to BannerId.GameplayAPlacedCardCapturesOnAll4SidesAtOnce,
        "gameplay_3_rematch_wins_in_a_row_against_the_same_opponent" to BannerId.Gameplay3RematchWinsInARowAgainstTheSameOpponent,
        "gameplay_3_rematch_losses_in_a_row_against_the_same_opponent" to BannerId.Gameplay3RematchLossesInARowAgainstTheSameOpponent,
        "gameplay_a_1_star_card_captures_3_cards_in_one_move" to BannerId.GameplayA1StarCardCaptures3CardsInOneMove,
        "gameplay_a_1_star_card_captures_a_5_star_card_rarity_mismatch" to BannerId.GameplayA1StarCardCapturesA5StarCardRarityMismatch,
        "gameplay_player_uses_undo_thinks_about_it_and_then_makes_the_exact" to BannerId.GameplayPlayerUsesUndoThinksAboutItAndThenMakesTheExact,
        "gameplay_player_plays_against_the_same_ai_difficulty_5_times_in_a_row" to BannerId.GameplayPlayerPlaysAgainstTheSameAiDifficulty5TimesInARow,
        "gameplay_player_wins_by_the_maximum_possible_margin" to BannerId.GameplayPlayerWinsByTheMaximumPossibleMargin,
        "milestones_first_launch_ever" to BannerId.MilestonesFirstLaunchEver,
        "milestones_player_reaches_10_total_wins" to BannerId.MilestonesPlayerReaches10TotalWins,
        "milestones_player_reaches_100_total_wins" to BannerId.MilestonesPlayerReaches100TotalWins,
        "milestones_player_reaches_1000_total_wins" to BannerId.MilestonesPlayerReaches1000TotalWins,
        "rule_specific_fallen_ace_triggers_a_1_captures_a_10" to BannerId.RuleSpecificFallenAceTriggersA1CapturesA10,
        "rule_specific_pollination_pushes_a_cards_modifier_to_3_or_higher" to BannerId.RuleSpecificPollinationPushesACardsModifierTo3OrHigher,
        "rule_specific_smoked_out_drops_a_cards_effective_stat_to_1" to BannerId.RuleSpecificSmokedOutDropsACardsEffectiveStatTo1,
        "rule_specific_a_player_triggers_a_plus_combo_the_math_matches_perfectly" to BannerId.RuleSpecificAPlayerTriggersAPlusComboTheMathMatchesPerfectly,
        "rule_specific_player_wins_flawless_opponent_score_0" to BannerId.RuleSpecificPlayerWinsFlawlessOpponentScore0,
        "rule_specific_player_loses_flawless_0_captures" to BannerId.RuleSpecificPlayerLosesFlawless0Captures,
        "rule_specific_roulette_rolls_pollination" to BannerId.RuleSpecificRouletteRollsPollination,
        "rule_specific_roulette_rolls_smoked_out" to BannerId.RuleSpecificRouletteRollsSmokedOut,
        "rule_specific_roulette_rolls_math_bee" to BannerId.RuleSpecificRouletteRollsMathBee,
        "rule_specific_roulette_rolls_inversion" to BannerId.RuleSpecificRouletteRollsInversion,
        "rule_specific_roulette_rolls_clear_skies" to BannerId.RuleSpecificRouletteRollsClearSkies,
        "rule_specific_roulette_rolls_scouting_party" to BannerId.RuleSpecificRouletteRollsScoutingParty,
        "rule_specific_roulette_rolls_frenzy" to BannerId.RuleSpecificRouletteRollsFrenzy,
        "rule_specific_roulette_rolls_symmetry" to BannerId.RuleSpecificRouletteRollsSymmetry,
        "rule_specific_roulette_rolls_nectar_exchange" to BannerId.RuleSpecificRouletteRollsNectarExchange,
        "rule_specific_roulette_rolls_hierarchy" to BannerId.RuleSpecificRouletteRollsHierarchy,
        "loading_game_loads_on_earth_day_apr_22" to BannerId.LoadingGameLoadsOnEarthDayApr22,
        "loading_game_loads_on_national_honey_day_aug_15" to BannerId.LoadingGameLoadsOnNationalHoneyDayAug15,
        "loading_game_loads_on_pi_day_mar_14" to BannerId.LoadingGameLoadsOnPiDayMar14,
        "loading_game_loads_on_new_years_eve_dec_31" to BannerId.LoadingGameLoadsOnNewYearsEveDec31,
        "loading_game_loads_on_christmas_dec_25" to BannerId.LoadingGameLoadsOnChristmasDec25,
        "loading_game_loads_on_holi" to BannerId.LoadingGameLoadsOnHoli,
        "loading_game_loads_on_rosh_hashanah" to BannerId.LoadingGameLoadsOnRoshHashanah,
        "loading_game_loads_on_diwali" to BannerId.LoadingGameLoadsOnDiwali,
        "loading_game_loads_on_eid_al_fitr" to BannerId.LoadingGameLoadsOnEidAlFitr,
        "loading_game_loads_on_hanukkah" to BannerId.LoadingGameLoadsOnHanukkah,
        "gameplay_player_runs_out_of_credits_video_poker_blackjack" to BannerId.GameplayPlayerRunsOutOfCreditsVideoPokerBlackjack,
    )
    fun parse(id: String): BannerId = ById[id] ?: error("Unknown BannerId: $id")
}
