// GENERATED FILE — do not hand-edit.
// Regenerate via `python3 tools/generate_localization.py` from
// Honeycomb_Localization.xlsx.

enum StringsSpanish {
    static let table: [StringKey: String] = [
        .newGame: "Nueva Partida",
        .restart: "Reiniciar",
        .undo: "Deshacer",
        .cancel: "Cancelar",
        .ok: "Aceptar",
        .done: "Hecho",
        .hint: "Pista",
        .options: "Opciones",
        .preferences: "Preferencias",
        .viewStats: "Ver Estadísticas",
        .visualThemes: "Temas Visuales",
        .visualThemesSubtitle: "Fieltro, reverso de carta, arte de figuras, colores",
        .language: "Idioma",
        .languageEnglish: "English",
        .languageSpanish: "Español",
        .resetStatisticsTitle: "¿Restablecer Estadísticas?",
        .resetStatisticsBody: "Esto borrará permanentemente todas las estadísticas del juego actual. Esta acción no se puede deshacer.",
        .reset: "Restablecer",
        .scoreLabel: "PUNTUACIÓN",
        .movesLabel: "MOVIMIENTOS",
        .timeLabel: "TIEMPO",
        .save: "Guardar",
        .delete: "Eliminar",
        .remove: "Quitar",
        .add: "Añadir…",
        .addShort: "Añadir",
        .edit: "Editar",
        .back: "Atrás",
        .close: "Cerrar",
        .errorTitle: "Error",
        .yes: "Sí",
        .soundEffects: "Efectos de Sonido",
        .soundShort: "Sonido",
        .noStressMode: "Modo Sin Estrés",
        .honeyMode: "Modo Miel (Sabor)",
        .hideHintButton: "Ocultar Botón de Pista",
        .manuallyDismissBanners: "Cerrar Anuncios Manualmente",
        .vegasScoring: "Puntuación Estilo Vegas",
        .vegasScoringMode: "Modo de Puntuación Vegas",
        .alwaysOnTop: "Siempre Visible",
        .timed: "Cronometrado",
        .hideBetBoard: "Ocultar Panel de Apuestas",
        .startingCreditsFmt: "Créditos Iniciales: %d",
        .dealerLabel: "REPARTIDOR",
        .playerLabel: "JUGADOR",
        .vsDivider: "VS",
        .youWin: "¡Ganaste!",
        .gameOver: "Juego Terminado",
        .noMovesRemaining: "No quedan movimientos.",
        .restartGame: "Reiniciar Partida",
        .victoryGuaranteed: "¡La victoria está garantizada!",
        .autocompleteGame: "Autocompletar Partida",
        .playAgain: "Jugar de Nuevo",
        .noHintsAvailable: "¡Lo sentimos! No hay pistas disponibles.",
        .newGameConfirmTitle: "¿Iniciar una nueva partida? Tu partida actual terminará.",
        .scoreFmt: "Puntuación: %@",
        .bankrollFmt: "Saldo: %@",
        .gamesPlayed: "Partidas Jugadas",
        .gamesWon: "Partidas Ganadas",
        .highScore: "Puntuación Máxima",
        .winPercentage: "Porcentaje de Victorias",
        .currentStreak: "Racha Actual",
        .longestStreak: "Racha Más Larga",
        .avgWinningTime: "Tiempo Promedio de Victoria",
        .fastestWin: "Victoria Más Rápida",
        .resetStats: "Restablecer Estadísticas",
        .resetStatisticsBodyGeneric: "Esto borrará permanentemente todas las estadísticas. Esta acción no se puede deshacer.",
        .handsPlayed: "Manos Jugadas",
        .handsWon: "Manos Ganadas",
        .winRate: "Tasa de Victorias",
        .totalWagered: "Total Apostado",
        .totalPaid: "Total Pagado",
        .biggestPay: "Mayor Pago",
        .rtpStat: "RTP",
        .rebuysStat: "Recompras",
        .royalFlushes: "Escaleras Reales",
        .deckCount1: "1 Baraja",
        .deckCount2: "2 Barajas",
        .suitCount1: "1 Palo",
        .suitCount2: "2 Palos",
        .suitCount4: "4 Palos",
        .manageDecks: "Administrar Mazos",
        .rematch: "Revancha",
        .newMatch: "Nueva Partida",
        .notTodayPartner: "¡Hoy no, compañero!",
        .cardAddedToBank: "Carta añadida al banco de cartas.",
        .cardBankFullLine1: "Tu banco de cartas está lleno. Empieza de nuevo en administrar mazos para robar otra vez.",
        .cardBankFullLine2: "Todos sus secretos, ahora tuyos. No queda nada por robar.",
        .obtainedAllCardsFmt: "Has obtenido todas las cartas de la mano de %@.",
        .rematchToTakeAnother: "Juega la revancha para tomar otra.",
        .stealProtectionLine: "La colmena se apiada de ti — una carta rara encuentra el camino a casa.",
        .stealCard: "Robar Carta",
        .confirmStealTitle: "¿Seguro que quieres robar esta carta?",
        .stealInstruction: "Haz doble clic en una carta capturada del oponente\nen el tablero para robarla.",
        .sillyBeeWarning: "No puedes vetar todas las partidas, abejita tonta.",
        .startOver: "Empezar de Nuevo",
        .startOverTitle: "¿Empezar de Nuevo?",
        .startOverBody: "¿Quieres empezar de cero? Empezar de nuevo borra tus mazos guardados y tu banco de cartas, y reinicia el juego con un conjunto de cartas completamente nuevo.",
        .startOverAlertBody: "Empezar de nuevo reinicia el juego con un conjunto de cartas completamente nuevo. Se perderán todos los mazos guardados y el progreso del banco de cartas. Esta acción no se puede deshacer.",
        .emptySlotFmt: "Ranura Vacía %d",
        .deckActiveBadge: "Activo",
        .deckSetActive: "Establecer como Activo",
        .deckCreate: "Crear",
        .allStarsFilter: "Todas las Estrellas",
        .starCountFmt: "%d★",
        .allSuitsFilter: "Todos los Palos",
        .suitSpades: "♠ Picas",
        .suitHearts: "♥ Corazones",
        .suitDiamonds: "♦ Diamantes",
        .suitClubs: "♣ Tréboles",
        .favoritesFilter: "Favoritos",
        .clearFilters: "Borrar",
        .deckBuilderTitle: "Constructor de Mazos",
        .deckRulesHint: "Máximo una carta de 5★ y una de 4★ por mazo. Se pueden usar dos cartas de 4★ sin una de 5★.",
        .errTooMany5star: "Un mazo nunca puede contener más de una carta de 5★.",
        .err5star4starCombo: "Si tienes una carta de 5★, solo puedes tener una carta de 4★.",
        .errTooMany4star: "Un mazo nunca puede contener más de dos cartas de 4★.",
        .errNameTooLong: "El nombre del mazo no puede superar los 20 caracteres.",
        .cardBankCountFmt: "BANCO DE CARTAS (%d de %d)",
        .yourDeckCountFmt: "Tu Mazo (%d/5) — Toca para Quitar",
        .cardBankTapToAdd: "Banco de Cartas — Toca para Añadir",
        .dealButton: "Repartir",
        .rebuyButton: "Recomprar",
        .buyInButton: "Comprar Fichas",
        .hitSpaceToDeal: "Presiona Espacio para Repartir",
        .holdAll: "Retener Todas",
        .betMax: "Apuesta Máxima",
        .scoreYouFmt: "TÚ %d",
        .scoreDealerFmt: "%d REPARTIDOR",
        .appNavigationTitle: "Honeycomb: Suite de Cartas",
        .resetDefaultCardBacks: "Restablecer Reversos de Carta Predeterminados",
        .stayOnTop: "Mantener Siempre Visible",
        .helpKlondike: "Ayuda de Solitario Klondike",
        .helpFreecell: "Ayuda de Freecell",
        .helpSpider: "Ayuda de Solitario Spider",
        .helpVideopoker: "Ayuda de Video Póker",
        .helpBlackjack: "Ayuda de Video Blackjack",
        .helpHoneycomb: "Ayuda de Honeycomb",
        .helpThemes: "Ayuda de Temas",
        .aboutHoneycomb: "Acerca de Honeycomb",
        .appName: "Honeycomb",
        .cardSuiteLabel: "SUITE DE CARTAS",
        .versionFmt: "Versión %@",
        .copyrightNotice: "© 2026 Leahbee. Todos los derechos reservados.",
        .dedication: "Para Rhinestone.",
        .checkForUpdates: "Buscar Actualizaciones…",
        .checkingForUpdates: "Buscando actualizaciones…",
        .upToDate: "Ya tienes la última versión.",
        .checkAgain: "Buscar de Nuevo",
        .updateCheckFailed: "No se pudo buscar actualizaciones. Comprueba tu conexión a internet.",
        .tryAgain: "Intentar de Nuevo",
        .newerVersionAvailableFmt: "La versión %@ está disponible.",
        .viewRelease: "Ver Lanzamiento",
        .statusBankroll: "SALDO",
        .stockExhausted: "Mazo\nAgotado",
        .finalBankrollFmt: "Saldo final: %@",
        .autocompleteBodyKlondike: "Todas las cartas restantes se pueden mover a los fundamentos.",
        .autocompleteBodyOther: "Todas las cartas restantes se pueden ordenar en los fundamentos.",
        .hotkeyLegendKlondike: "Flechas=Mover Cursor   Espacio/Intro=Seleccionar o Mover   D=Robar   F=Auto-Fundamento   A=Autocompletar   Esc=Borrar Cursor",
        .hotkeyLegendBeecell: "Flechas=Mover Cursor   Espacio/Intro=Seleccionar o Mover   C=Celda Libre   F=Auto-Fundamento   A=Autocompletar   Esc=Borrar Cursor",
        .hotkeyLegendSpider: "Flechas=Mover Cursor   Espacio/Intro=Seleccionar o Mover   D=Repartir   A=Autocompletar   Esc=Borrar Cursor",
        .hotkeyLegendBlackjack: "Espacio=Repartir   H=Pedir   S=Plantarse   D=Doblar   P=Dividir",
        .hotkeyLegendVideopoker: "Espacio/Intro/D=Repartir o Robar   1-5=Alternar Retener   H=Retener Todas   C=Borrar   M=Apuesta Máxima",
        .restartConfirmTitle: "¿Reiniciar esta partida desde el principio?",
        .newGameConfirmTitleShort: "¿Iniciar una nueva partida?",
        .winSummaryWithTimeFmt: "%@ | Tiempo: %@",
        .drawModeLabel: "Modo de Robo:",
        .drawOne: "Robar Una",
        .drawThree: "Robar Tres",
        .faceCardsTitle: "Cartas de Figura",
        .cardColorsTitle: "Colores de Carta",
        .themesPanelTitle: "Temas",
        .addCustomCardArtHeading: "Añadir Arte de Carta Personalizado",
        .jpgPngAcceptedSuffix: "(se aceptan .jpg o .png):",
        .doubleClickAdjustBackgroundTooltip: "Haz doble clic para ajustar el fondo",
        .clickAdjustCardBackTooltip: "Haz clic para ajustar el reverso de la carta",
        .customFeltColorLabel: "Color de Fieltro Personalizado:",
        .customizeFaceCardsTitle: "Personalizar Cartas de Figura para el Tema",
        .customizeFaceCardsSubtitle: "16 ranuras — Ases, Jotas, Reinas, Reyes por palo",
        .customCardColorsTitle: "Colores de Carta Personalizados para el Tema",
        .customCardColorsSubtitleMac: "Fondo, contorno, texto de palo, resaltado de pista",
        .customCardColorsSubtitleWin: "Fondo, contorno, texto, resaltado de pista",
        .livePreviewNotice: "Vista previa en vivo — los cambios de abajo se aplican a estas cartas de inmediato.",
        .backgroundLabel: "Fondo:",
        .feltGreen: "Verde Fieltro",
        .feltCrimson: "Carmesí",
        .feltRoyalBlue: "Azul Real",
        .feltCharcoal: "Carbón",
        .feltDesert: "Desierto",
        .feltCustomColor: "Color de Fieltro Personalizado",
        .addCustomBackgroundOption: "Añadir Fondo Personalizado…",
        .feltVignetteToggle: "Viñeta de Fieltro",
        .deleteCurrentWallpaper: "Eliminar Fondo Actual",
        .couldNotSaveBackgroundError: "No se pudo guardar el fondo. La imagen puede estar dañada o el disco puede estar lleno.",
        .deleteBackgroundTitle: "Eliminar Fondo",
        .deleteBackgroundBody: "¿Seguro que quieres eliminar este fondo?",
        .backgroundInUseTitle: "Fondo en Uso",
        .couldNotLoadSelectedImageFileError: "No se pudo cargar el archivo de imagen seleccionado.",
        .fileMustBeJpgPngError: "¡El archivo debe ser .jpg o .png!",
        .imageTooLargeTitle: "Imagen Demasiado Grande",
        .imageTooLargeMessage: "Esa imagen pesa más de 25 MB. Por favor elige un archivo más pequeño.",
        .backgroundInvalidFormatWin: "El archivo seleccionado no es una imagen PNG o JPEG válida.",
        .backgroundInUseFmt: "Este fondo está siendo usado por \"%@\". Por favor actualiza o elimina el tema primero.",
        .editCustomBackgroundTitle: "Editar Fondo Personalizado",
        .backgroundNameLabel: "Nombre del Fondo:",
        .backgroundNamePlaceholder: "p. ej. Mi Escritorio",
        .horizontalPositionLabel: "Posición Horizontal:",
        .pxOffsetFmt: "%.0f px",
        .verticalPositionLabel: "Posición Vertical:",
        .scaleFactorLabel: "Factor de Escala:",
        .scaleFmt: "%.2fx",
        .nameEmptyOrExistsError: "¡El nombre no puede estar vacío o ya existir!",
        .editCardBackTitle: "Editar Reverso de Carta",
        .editCustomCardArtTitle: "Editar Arte de Carta Personalizado",
        .cardBackNameLabel: "Nombre del Reverso:",
        .cardBackNamePlaceholder: "p. ej. Mi Perro",
        .addNameToSaveError: "Añade un nombre para guardar.",
        .deleteDeckTooltip: "Eliminar mazo",
        .deleteCardBackTitle: "Eliminar Reverso de Carta",
        .deleteNamedCardBackConfirmFmt: "¿Seguro que quieres eliminar \"%@\"?",
        .deleteCardBackBody: "¿Seguro que quieres eliminar este reverso de carta personalizado? Esta acción no se puede deshacer.",
        .cardDeckHeading: "Mazo de Cartas",
        .jpgPngGifAcceptedSuffix: "(se aceptan .jpg, .png o .gif):",
        .addCustomDeck: "Añadir Personalizado…",
        .cardBackInUseTitle: "Reverso de Carta en Uso",
        .cardBackInUseFmt: "Este reverso de carta está siendo usado por \"%@\". Por favor actualiza o elimina el tema primero.",
        .cardBackInUseMultiThemeFmt: "Este reverso de carta está siendo usado por {0}. Por favor elimina el/los tema(s) primero.",
        .cardBackLastRemaining: "Debe quedar al menos un diseño de mazo — no puedes eliminar el último.",
        .customCardColorHeading: "Color de Carta Personalizado",
        .customCardColorsPanelTitle: "Colores de Carta Personalizados",
        .resetCardColors: "Restablecer Colores de Carta",
        .resetCardColorsConfirmBody: "¿Seguro que quieres restablecer los colores de carta a los predeterminados?",
        .cardBackgroundLabel: "Fondo de Carta",
        .cardOutlineLabel: "Contorno de Carta",
        .blackSuitTextLabel: "Texto de Palo Negro",
        .redSuitTextLabel: "Texto de Palo Rojo",
        .hintHighlightLabel: "Resaltado de Pista",
        .editFaceCardArtTitleFmt: "Editar Arte de %@%@",
        .scaleShortLabel: "Escala",
        .horizontalShortLabel: "Horizontal",
        .verticalShortLabel: "Vertical",
        .removeArtTooltip: "Quitar arte",
        .removeArtTitle: "Quitar Arte",
        .removeArtConfirmBody: "¿Quitar el arte personalizado de esta ranura?",
        .fileMustBeJpgPngGifError: "El archivo debe ser .jpg, .png o .gif.",
        .couldNotLoadSelectedImageError: "No se pudo cargar la imagen seleccionada.",
        .couldNotReadImageDataError: "No se pudieron leer los datos de la imagen.",
        .toggleGameModeLabel: "Modo de Juego:",
        .option1deck: "Estándar (1 Baraja)",
        .option2deck: "Dos Barajas (2 Barajas)",
        .freecellStatisticsFmt: "Estadísticas de Freecell (%@)",
        .gamesPlayedColon: "Partidas Jugadas:",
        .gamesWonColon: "Partidas Ganadas:",
        .highScoreColon: "Puntuación Máxima:",
        .winPercentageColon: "Porcentaje de Victorias:",
        .currentStreakColon: "Racha Actual:",
        .longestStreakColon: "Racha Más Larga:",
        .avgWinningTimeColon: "Tiempo Promedio de Victoria:",
        .fastestWinColon: "Victoria Más Rápida:",
        .resetBankrollButton: "Restablecer Saldo",
        .creditsLabel: "CRÉDITOS",
        .betLabel: "APUESTA",
        .handsLabel: "MANOS",
        .resultHeadlineBlackjack: "¡Blackjack!",
        .resultHeadlinePush: "Empate",
        .resultSubPush: "Apuestas devueltas",
        .resultHeadlineBust: "¡Te pasaste!",
        .resultSubNetPositiveFmt: "+%d créditos",
        .resultSubNetNegativeFmt: "%d créditos",
        .resultSubEven: "Empate en créditos",
        .resultDealerValueFmt: "Repartidor: %d",
        .resultPlayerValueFmt: "Jugador: %d",
        .streakText5plusFmt: "*** RACHA DE %d VICTORIAS ***",
        .streakText3to4Fmt: "** RACHA DE %d VICTORIAS **",
        .streakText2Fmt: "¡%d victorias seguidas!",
        .btnClearBet: "BORRAR APUESTA",
        .btnClearBetWin: "Borrar Apuesta",
        .btnDealSpace: "REPARTIR  [Espacio]",
        .btnDealSpaceWin: "Repartir  [Espacio]",
        .btnRebuyMac: "RECOMPRAR",
        .btnHit: "PEDIR  [H]",
        .btnHitWin: "Pedir  [H]",
        .btnStand: "PLANTARSE  [S]",
        .btnStandWin: "Plantarse  [S]",
        .btnDouble: "DOBLAR  [D]",
        .btnDoubleWin: "Doblar  [D]",
        .btnSplit: "DIVIDIR  [P]",
        .btnSplitWin: "Dividir  [P]",
        .keyHintRowWin: "Espacio/Intro=Repartir   H=Pedir   S=Plantarse   D=Doblar   P=Dividir",
        .chipAmountFmt: "+%d",
        .chip1: "1",
        .chip5: "5",
        .chip10: "10",
        .chip25: "25",
        .chip2x: "2X",
        .blackjackStatistics: "Estadísticas de Blackjack",
        .statHandsLost: "Manos Perdidas",
        .statPushes: "Empates",
        .statBlackjacks: "Blackjacks",
        .statCurStreakShort: "Racha Act.",
        .statBestStreak: "Mejor Racha",
        .msgResetStatsBlackjack: "Esto borrará permanentemente todas las estadísticas de Blackjack. Esta acción no se puede deshacer.",
        .emptyColumnWarningTitle: "Advertencia de Columna Vacía",
        .emptyColumnWarningBody: "Todas las columnas del tablero deben tener al menos una carta antes de repartir desde el mazo.",
        .pickerSuitsLabel: "Palos:",
        .optionSuits1: "1 (Picas)",
        .optionSuits2: "2 (♠♥)",
        .optionSuits4: "4 (Estándar)",
        .spiderStatisticsFmt: "Estadísticas de Spider (%d %@)",
        .labelSuitSingular: "Palo",
        .labelSuitPlural: "Palos",
        .statAverageWinTime: "Tiempo Promedio de Victoria",
        .noTimePlaceholder: "--",
        .betHandLabel: "APUESTA/MANO",
        .totalBetLabel: "APUESTA TOTAL",
        .payTableMaxCol: "MÁX",
        .resultHandNameFmt: "¡%@!",
        .resultCreditsWonFmt: "+%d Créditos",
        .resultCreditsLostFmt: "-%d créditos",
        .minusCreditsSuffix: "créditos",
        .btnBetMinus: "-",
        .btnBetMaxMac: "APUESTA MÁXIMA  [M]",
        .btnBetPlus: "+",
        .btnHoldAllMac: "RETENER TODAS  [H]",
        .btnHoldAllWin: "Retener Todas  [H]",
        .btnClearHoldsMac: "BORRAR  [C]",
        .btnClearHoldsWin: "Borrar  [Q]",
        .btnDraw: "ROBAR",
        .btnDrawWinMinus: "− Apuesta",
        .btnDrawWinPlus: "+ Apuesta",
        .tapHoldDrawHint: "Toca las cartas para retenerlas, luego Roba",
        .heldLabel: "RETENIDA",
        .payoutResultFmt: "%@  +%d",
        .pickerVariantLabel: "Variante:",
        .pickerPlaymodeLabel: "Modo de Juego:",
        .pickerDefaultBetLabel: "Apuesta Predeterminada:",
        .optionCoinCountFmt: "%d moneda%@",
        .variantJacksOrBetter: "Jotas o Mejor",
        .variantDeucesWild: "Doses Salvajes",
        .variantBonusPoker: "Póker Bono",
        .videoPokerStatistics: "Estadísticas de Video Póker",
        .toolbarStartMatch: "Iniciar Partida",
        .toolbarQuitMatch: "Abandonar Partida",
        .toolbarRules: "Reglas",
        .honeycombRulesTitle: "Reglas de Honeycomb",
        .statusYouLabel: "Tú",
        .rulesBannerTitle: "Reglas:",
        .ruleLineNormal: "Normal",
        .ruleLineRoulette: "Ruleta",
        .ruleLineSuitFmt: "Palo %@: %@",
        .handLabelYou: "TÚ",
        .quitButton: "Abandonar",
        .startButton: "Iniciar",
        .noHintsBanner: "¡No hay pistas para esta!",
        .takeACardButton: "Toma una Carta",
        .dismissA11y: "Cerrar",
        .settingsHeader: "HONEYCOMB",
        .opponentPickerLabel: "Oponente",
        .forceNormalRulesToggle: "Forzar Reglas Normales",
        .toggleNormalModeMac: "Modo Normal (Forzar Cero Reglas)",
        .matchRulesDisclosure: "Reglas de la Partida",
        .rulesColumnTitle: "Elección de Juego",
        .matchRulesHint: "Selecciona hasta 4 reglas. Déjalo vacío para que la ruleta decida las reglas de cada partida.",
        .banListDisclosure: "Lista de Vetados",
        .banListHintMac: "Selecciona partidas para vetar de las ruletas.",
        .normalModeBanItem: "Modo Normal",
        .settingsUnlockNote: "La configuración se desbloquea cuando termina la partida.",
        .statsSheetTitle: "Estadísticas de Honeycomb",
        .honeycombStatistics: "Estadísticas de Honeycomb",
        .statMatchesPlayed: "Partidas Jugadas",
        .statMatchesWon: "Partidas Ganadas",
        .statMatchesLost: "Partidas Perdidas",
        .statMatchesDrawn: "Partidas Empatadas",
        .statCardsCaptured: "Cartas Capturadas",
        .statCardsStolen: "Cartas Robadas",
        .statCurrentWinStreak: "Racha Actual de Victorias",
        .statLongestWinStreak: "Racha Más Larga de Victorias",
        .statFlawlessVictoriesIos: "Victorias Perfectas",
        .statFlawlessVictoriesMac: "Victorias Perfectas (Barrida 10-0)",
        .statSamePlusTriggers: "Activaciones Same/Plus",
        .statWinsByDifficultySection: "Victorias por Dificultad",
        .statBabyBee: "Abeja Bebé",
        .statHoneyBee: "Abeja de Miel",
        .statQueenBee: "Abeja Reina",
        .statKillerBee: "Abeja Asesina",
        .statBabyBeeWins: "Victorias Abeja Bebé",
        .statHoneyBeeWins: "Victorias Abeja de Miel",
        .statQueenBeeWins: "Victorias Abeja Reina",
        .statKillerBeeWins: "Victorias Abeja Asesina",
        .statSwarmsToDeath: "Más Enjambres a Muerte",
        .statTotalCardsFlipped: "Total de Cartas Volteadas",
        .statQueensFalls: "Caídas de la Reina",
        .statHiveMindsTriggered: "Mentes Colmena Simetría/Abeja Matemática Activadas",
        .statTimesStartedOver: "Veces Reiniciado",
        .statCardsUnlockedLabel: "Cartas Desbloqueadas",
        .statCardsUnlockedValueFmt: "%d/%d (%@)",
        .statSuitUnlockedFmt: "%@ Desbloqueado",
        .statStarUnlockedFmt: "%d★ Desbloqueado",
        .tieResult: "¡Empate!",
        .finalScoreFmt: "Puntuación Final: {0} - {1}",
        .sheetTitleMac: "Mazos Guardados y Banco de Cartas",
        .tabSavedDecks: "Mazos Guardados",
        .tabCardBank: "Banco de Cartas",
        .statSearchHint: "Búsqueda libre: escribe un valor sobre la carta para filtrar el banco.",
        .savedDecksHeader: "MAZOS GUARDADOS",
        .deckNamePlaceholder: "Nombre del Mazo (Máx. 20 caracteres)",
        .deckNamePlaceholderIos: "Nombre del Mazo (máx. 20 caracteres)",
        .enterDeckNameHint: "Ingresa un nombre de mazo para guardar.",
        .contextRemoveFromDeck: "¿Quitar del mazo?",
        .btnSaveDeck: "Guardar Mazo",
        .deckSlotDefaultNameFmt: "Mazo %d",
        .klondikeStatisticsTitle: "Estadísticas de Klondike",
        .vegasBankrollLabel: "Saldo Vegas:",
        .handHighCard: "Carta Alta",
        .handOnePair: "Un Par",
        .handTwoPair: "Dos Pares",
        .handThreeOfAKind: "Tercia",
        .handStraightFlush: "Escalera de Color",
        .handFourOfAKind: "Póker",
        .handFullHouse: "Full House",
        .handFiveOfAKind: "Repóker",
        .handFourAces: "Cuatro Ases",
        .handFour2s4s: "Cuatro 2s-4s",
        .handFourDeuces: "Cuatro Doses",
        .handNaturalRoyalFlush: "Escalera Real Natural",
        .handWildRoyalFlush: "Escalera Real Comodín",
        .handNoWin: "Sin Premio",
        .difficultyUltraHardRawvalue: "Ultra Difícil",
        .ruleNameCappedBrood: "Cría Sellada",
        .ruleNameNectarExchange: "Intercambio de Néctar",
        .ruleNameScoutingParty: "Grupo de Exploración",
        .ruleNameSwarmToTheDeath: "Enjambre a Muerte",
        .ruleExplanationChaos: "Obliga aleatoriamente qué carta se debe jugar en cada turno.",
        .ruleExplanationReverse: "Invierte todas las comparaciones—las estadísticas más bajas vencen a las más altas.",
        .normalModeBanListTooltip: "Fuerza una partida sin reglas activas, saltándose la ruleta.",
        .gamemodeKlondikeDisplay: "Klondike Solibee",
        .gamemodeSpiderDisplay: "Spider Solibee",
        .playmodeSingle: "Partida Única",
        .playmodeTriple: "Partida Triple",
        .gameSelectionLabel: "Selección de Juego",
        .hintRecycleWasteToStock: "Reciclar pila de descarte al mazo.",
        .themeNameFieldPlaceholder: "Nombre del tema",
        .themeNameEmptyError: "El nombre del tema no puede estar vacío.",
        .themeNameExistsErrorFmt: "Ya existe un tema llamado \"%@\".",
        .renameThemeTitle: "Renombrar Tema",
        .saveAsNewTheme: "Guardar como Nuevo Tema",
        .noSavedThemesYet: "Aún no hay temas guardados.",
        .deleteThemeTitle: "Eliminar Tema",
        .applyThemeButton: "Aplicar",
        .deleteThemeConfirmFmt: "¿Eliminar \"%@\"? Esta acción no se puede deshacer.",
        .helpHoneycombSubtitle: "Una batalla táctica de cartas en cuadrícula de 3×3 inspirada en Triple Triad.",
        .helpCoreGameplayMechanicsTitle: "🎮 Jugabilidad Principal y Mecánicas",
        .helpHowToPlayVariantsTitle: "🎮 Cómo Jugar y Variantes",
        .helpStrategyProTipsTitle: "💡 Estrategia y Consejos Pro",
        .helpOverviewObjectiveTitle: "📌 Resumen y Objetivo",
        .helpControlsShortcutsTitle: "⌨️ Controles y Atajos",
        .helpShortcutClickDragTap: "Haz clic y arrastra o Toca Carta → Toca Celda",
        .helpShortcutNavigateSelect: "Navegar / Seleccionar",
        .helpShortcutSelectPlaceCard: "Seleccionar / Colocar Carta",
        .helpShortcutSelectPlaceSequence: "Seleccionar / Colocar Secuencia",
        .helpShortcutShowBestAiMove: "Mostrar Mejor Movimiento de la IA",
        .helpShortcutSplitPairs: "Dividir Pares",
        .helpShortcutArrowKeys: "Teclas de Flecha",
        .helpShortcutCQ: "C / Q",
        .helpShortcutSpaceEnter: "Espacio / Intro",
        .helpShortcutCmdNR: "⌘N / ⌘R",
        .helpShortcutCmdZ: "⌘Z",
        .helpBeecellTitle: "Freecell (Beecell)",
        .helpKlondikeObjective: "Mueve las 52 cartas a las cuatro pilas de la Fundación, organizadas por palo desde el As (el más bajo) hasta el Rey (el más alto).",
        .helpKlondikeLayout: "• Tablero (7 Columnas): Repartidas de izquierda a derecha con 1 a 7 cartas respectivamente. Solo la carta superior de cada columna está boca arriba.\n• Pila (Arriba a la Izquierda): Contiene las 24 cartas restantes boca abajo.\n• Descarte (Junto a la Pila): Contiene las cartas robadas de la pila.\n• Fundaciones (Arriba a la Derecha): Cuatro espacios vacíos reservados para completar cada palo.",
        .helpKlondikeRules: "• Construcción del Tablero: Apila cartas en rango descendente alternando colores (ej., un 6 rojo sobre un 7 negro). Puedes mover una sola carta o una secuencia entera boca arriba a otra columna.\n• Columnas Vacías: Solo un Rey (o una secuencia que empiece con un Rey) puede colocarse en una columna vacía del tablero.\n• Pila y Descarte:\n  – Modo Robar 1: Al hacer clic en la pila se revela 1 carta al descarte.\n  – Modo Robar 3: Revela 3 cartas; solo la carta superior del descarte es jugable. Una vez jugada, la siguiente carta del grupo de 3 estará disponible.\n• Modos de Puntuación:\n  – Estándar: Voltear carta boca abajo (+5 pts) · Descarte al Tablero (+5 pts) · Descarte/Tablero a la Fundación (+10 pts) · Fundación de vuelta al Tablero (−15 pts).\n  – Vegas: Empiezas con una deuda de −$52. Gana +$5 por cada carta movida a la fundación. Robar 1 permite solo 1 pasada por la pila; Robar 3 permite 3 pasadas (2 repartos extra).",
        .helpKlondikeStrategy: "1. Prioriza Cartas Boca Abajo: Siempre prioriza movimientos que revelen cartas ocultas en las columnas más largas del tablero.\n2. Mantén Columnas Abiertas: No vacíes una columna del tablero a menos que ya tengas un Rey listo para ocuparla.\n3. Retrasa Movimientos a la Fundación: Evita apresurar cartas a la fundación temprano si podrían necesitarse para construir secuencias más bajas en el tablero.",
        .helpKlondikeNoStress: "Activar el Modo Sin Estrés en Opciones desactiva el temporizador de la partida por completo.",
        .helpBeecellObjective: "Mueve las 52 cartas a las cuatro pilas de la Fundación, construyéndolas por palo desde el As hasta el Rey.",
        .helpBeecellLayout: "• Tablero (8 Columnas): Las 52 cartas se reparten boca arriba al inicio (4 columnas de 7 cartas, 4 columnas de 6 cartas).\n• Celdas Libres (Arriba a la Izquierda): Cuatro espacios de almacenamiento temporal.\n• Fundaciones (Arriba a la Derecha): Cuatro pilas de construcción por palo.",
        .helpBeecellRules: "• Construcción del Tablero: Apila cartas en rango descendente y colores alternos.\n• Almacenamiento en Celdas Libres: Cada celda libre puede contener exactamente 1 carta a la vez.\n• Capacidad de Movimiento Múltiple: Puedes mover una secuencia de cartas boca arriba en una sola acción. El número máximo de cartas que puedes mover a la vez se calcula como: (Celdas Libres Disponibles + 1) × 2^(Columnas Vacías en el Tablero).\n• Columnas Vacías: Cualquier carta individual o secuencia válida se puede mover a una columna vacía en el tablero.",
        .helpBeecellStrategy: "1. Protege Tus Celdas Libres: Trata las celdas libres como espacio de maniobra temporal. Evita llenar las cuatro celdas libres simultáneamente, ya que reduce drásticamente tu capacidad de mover secuencias.\n2. Descubre Cartas Bajas Temprano: Concéntrate en liberar Ases y Doses enterrados al fondo de las columnas.\n3. Las Columnas Vacías son Oro: Una columna vacía duplica tu capacidad de movimiento y actúa como una celda libre sin restricciones.",
        .helpSpiderObjective: "Arma ocho secuencias completas del mismo palo desde el Rey hasta el As dentro del tablero. Cada secuencia completa de 13 cartas se elimina automáticamente a la fundación.",
        .helpSpiderLayout: "• Tablero (10 Columnas): 54 cartas repartidas en 10 columnas (las primeras 4 tienen 6 cartas; las últimas 6 tienen 5 cartas). Solo la carta superior de cada columna está boca arriba.\n• Pila (Abajo/Arriba): Las 50 cartas restantes organizadas en 5 repartos extra de 10 cartas cada uno.",
        .helpSpiderRules: "• Modos de Dificultad:\n  – 1 Palo (Fácil): Las 104 cartas son Picas.\n  – 2 Palos (Medio): 52 Picas y 52 Corazones.\n  – 4 Palos (Difícil): Se usan los cuatro palos estándar.\n• Construcción del Tablero: Apila cartas en rango descendente sin importar el palo (ej., un 7 de Corazones puede colocarse sobre un 8 de Picas). Excepción Crucial: Solo puedes mover una secuencia de múltiples cartas si todas las cartas de esa secuencia comparten el mismo palo.\n• Repartos desde la Pila: Haz clic en la pila para repartir 1 carta en cada columna del tablero. Requisito: Cada columna debe contener al menos 1 carta antes de que puedas repartir desde la pila.",
        .helpSpiderStrategy: "1. Mismo Palo Antes que Palos Mixtos: Siempre prefiere construir rachas del mismo palo. Las pilas de palos mixtos bloquean tus cartas y no pueden moverse juntas.\n2. Columnas Vacías Primero: Las columnas vacías te permiten aislar pilas de palos mixtos y reorganizarlas en limpias rachas del mismo palo.\n3. Retrasa el Reparto: Agota cada movimiento posible en el tablero antes de hacer clic en la pila.",
        .helpVideopokerObjective: "Roba una mano de 5 cartas que coincida con una entrada válida en la tabla de pagos para ganar multiplicadores de créditos.",
        .helpVideopokerHowToPlay: "1. Apuestas: Selecciona 1 a 5 monedas. Presiona Apuesta Máxima (M) para apostar 5 monedas y repartir de inmediato. (Nota: El premio de 800× por la Escalera Real solo se otorga con una apuesta de 5 monedas).\n2. Repartir y Retener: Presiona Repartir (Espacio). Haz clic en las cartas o presiona 1–5 para alternar RETENER (HOLD) en las cartas que desees guardar.\n3. Robar: Presiona Robar (Espacio). Las cartas no retenidas son reemplazadas. Las ganancias se pagan según la tabla de pagos.\n\nVariantes de Juego:\n• Jacks or Better: Tabla de pagos estándar. La mano mínima para calificar es un par de Jotas, Reinas, Reyes o Ases (1×).\n• Deuces Wild: Los cuatro 2s son comodines. La mano ganadora mínima es Tercia. Pagos especiales por Cuatro Doses (200×) y Escalera Real Comodín (25×).\n• Bonus Poker: Pagos mejorados por Póker (Cuatro Ases paga 80×; Cuatro 2s/3s/4s paga 40×).",
        .helpVideopokerStrategy: "1. Siempre Haz Apuesta Máxima (5 Monedas): El pago por la Escalera Real salta de 250× a 800× solo con 5 monedas.\n2. Nunca Rompas una Mano Armada (Excepto por 4-para-Escalera Real): Solo rompe una Escalera o Color si estás a 1 carta de una Escalera Real.\n3. En Deuces Wild, Nunca Descartes un 2: Los dos son comodines—¡siempre retén cada 2 que te repartan!",
        .helpVideopokerNoStress: "Activar el Modo Sin Estrés en Opciones cambia el juego a Juego Libre—ocultando apuestas, créditos y tablas de pagos para que puedas jugar sin riesgos ni apuestas.",
        .helpBlackjackObjective: "Supera el total de la mano del repartidor sin pasarte de 21. Cartas de Figura = 10, Ases = 1 u 11, Cartas Numéricas = valor nominal.",
        .helpBlackjackRules: "1. Haz Apuesta y Reparte: Selecciona tu apuesta en fichas (1, 5, 10, 25) o presiona Apuesta Máxima (M), luego presiona Repartir (Espacio).\n2. Tu Turno:\n  – Pedir (H): Toma otra carta.\n  – Plantarse (S): Mantén tu mano actual.\n  – Doblar (D): Dobla tu apuesta, recibe exactamente 1 carta, y te plantas automáticamente. (Disponible en las 2 cartas iniciales con un total de 9, 10, u 11).\n  – Dividir (P): Si se te reparten dos rangos iguales, divídelos en dos manos separadas (requiere una segunda apuesta igual).\n3. Turno del Repartidor: El repartidor revela su carta oculta y debe pedir hasta alcanzar 17 o más (se planta en todos los 17s).\n\nEsquema de Pagos:\n• Ganancia Estándar: pago 1:1.\n• Blackjack Natural (As + carta de valor 10): pago 3:1.\n• Empate (Push): Se devuelve la apuesta.",
        .helpBlackjackStrategy: "1. Siempre Divide Ases y 8s: Nunca dividas 10s o 5s.\n2. Dobla con 11: Siempre Dobla cuando tu mano inicial sume 11 contra un repartidor del 2 al 10.\n3. Observa la Carta Abierta del Repartidor: Si el repartidor muestra del 2 al 6, tiene una alta probabilidad de pasarse—plántate con 12 duro o más y deja que el repartidor robe.",
        .helpBlackjackNoStress: "Activar el Modo Sin Estrés en Opciones cambia el juego a Juego Libre—ocultando apuestas y créditos para que puedas jugar sin riesgos ni apuestas.",
        .helpHoneycombObjective: "Lucha contra un oponente de la IA en una cuadrícula de 3×3 usando un mazo de 5 cartas. Cada carta cuenta con 4 estadísticas direccionales (Arriba, Derecha, Abajo, Izquierda). Coloca las cartas estratégicamente para voltear las cartas enemigas a tu color. ¡Quien controle la mayoría de las 9 celdas al final gana!",
        .helpHoneycombMechanics: "• Capturas: Cuando colocas una carta adyacente a la de un oponente, tu estadística de cara se compara con su estadística de cara opuesta. Si tu estadística es mayor, la carta enemiga es capturada (volteada a tu color). La estadística 10 se representa como \"A\".\n• Mentes Colmena: ¡Una carta capturada durante un turno revisa de inmediato a sus propios vecinos adyacentes, desencadenando una secuencia de captura en reacción en cadena!",
        .helpHoneycombCardBank: "• Mecánica de Robo: Después de ganar una partida, ¡haz doble clic en una carta elegible del repartidor para robarla permanentemente hacia tu Banco de Cartas! Solo se permite un robo por partida.\n• Límites de Rareza de Mazo: Los mazos personalizados están limitados a: como máximo una carta de 5★, y como máximo una carta de 4★ si hay una de 5★ presente (o hasta dos cartas de 4★ sin una de 5★).\n• Mazos de Oponente Inteligentes: La IA selecciona automáticamente mazos que contienen cartas que aún no tienes para maximizar las recompensas de robo.\n• Protección Anti-Robo: ¿Atrapado en una cadena de Revanchas contra un oponente cuyas cartas parece que no puedes capturar? Gana dos Revanchas seguidas contra el mismo oponente sin que haya nada elegible para robar, y cualquier carta aún no desbloqueada que quede en el tablero se vuelve robable en esa segunda victoria — capturada o no. Una vez activada, se mantiene activa para el resto de esa cadena de Revanchas, para que cada victoria futura siga ofreciendo un robo — no tendrás que volver a ganarlo. Comenzar una Nueva Partida (un nuevo oponente) es lo que la desactiva.",
        .helpHoneycombNoStress: "Activar el Modo Sin Estrés en Opciones te proporciona un mazo fuerte fijo en cada partida y oculta las mecánicas de Robo de Cartas.",
        .helpCustomizationThemes: "• Mesa de Fieltro: Elige entre 5 colores de fieltro preestablecidos (Verde, Carmesí, Azul Real, Carbón, Desierto) o establece un Color Personalizado. Activa/desactiva la viñeta de los bordes.\n• Reversos de Cartas: Selecciona diseños incorporados o sube archivos .jpg/.png/.gif personalizados.\n• Arte de Cartas de Figura: Sube arte de imagen/GIF personalizado individualmente para Ases, Jotas, Reinas y Reyes.\n• Temas Guardados: ¡Guarda un instante de tu fieltro, reversos de cartas y arte de figuras en temas personalizados con nombre para aplicarlos en cualquier momento con un solo clic!",
        .helpCustomizationOptions: "• Modo Miel (Sabor): Interruptor global en los 6 juegos — controla las ventanas emergentes de puntuación \"+N\"/\"-N\" y si aparecen los carteles de sabor/ambiente. Desactívalo para una experiencia de juego más silenciosa y minimalista.\n• Siempre Encima: Mantiene la ventana del juego anclada sobre tus otras ventanas (Menú Vista).\n• Efectos de Sonido, Puntuación Vegas, y Ocultar Botón de Pistas también están disponibles aquí por juego.",
        .helpKlondikeTitle: "Solitario Klondike",
        .helpKlondikeSubtitle: "Clásico solitario de un mazo con opciones de Robar 1, Robar 3 y puntuación Vegas.",
        .helpBeecellSubtitle: "El juego de solitario estratégico definitivo: el 99.9% de los repartos tienen solución.",
        .helpSpiderTitle: "Solitario Spider",
        .helpSpiderSubtitle: "Un juego profundo de dos mazos sobre construcción de secuencias con 1, 2 o 4 palos.",
        .helpVideopokerTitle: "Video Póker",
        .helpVideopokerSubtitle: "Póker clásico de casino con tablas de pagos de Jacks or Better, Deuces Wild y Bonus Poker.",
        .helpBlackjackTitle: "Video Blackjack",
        .helpBlackjackSubtitle: "Vence al repartidor acercándote más a 21 sin pasarte.",
        .helpThemesTitle: "Temas y Configuración Global",
        .helpThemesSubtitle: "Personaliza la apariencia de cada juego y ajusta los modos globales.",
        .helpSetupLayoutTitle: "🃏 Preparación y Disposición",
        .helpRulesHowToPlayTitle: "🎮 Reglas y Cómo Jugar",
        .helpRulesOptionsTitle: "🎮 Reglas y Opciones",
        .helpMatchModifiersTitle: "🎲 Modificadores de Partida y Reglas Especiales",
        .helpCardBankStealingTitle: "🏆 Banco de Cartas y Robos",
        .helpThemesCustomizationTitle: "🎨 Temas y Personalización",
        .helpOptionsTitle: "⚙️ Opciones",
        .helpShortcutNavigateBoardCursor: "Navegar Cursor del Tablero",
        .helpShortcutClearSelection: "Borrar Selección",
        .helpShortcutDrawCards: "Robar Carta(s)",
        .helpShortcutAutoMoveFoundation: "Mover Automáticamente a la Fundación",
        .helpShortcutNewGameRestartDeal: "Nueva Partida / Reiniciar Reparto",
        .helpShortcutUndoMove: "Deshacer Movimiento",
        .helpShortcutToggleDraw: "Alternar Robar 1 / Robar 3",
        .helpShortcutCycleHints: "Alternar Pistas Disponibles",
        .helpShortcutHintButton: "Botón de Pista",
        .helpShortcutAutoParkFreeCell: "Aparcar Automáticamente en Celda Libre",
        .helpShortcutArrowSpaceEnter: "Teclas de Flecha + Espacio / Intro",
        .helpShortcutDeal10Cards: "Repartir 10 Cartas de la Pila",
        .helpShortcut1suit2suitMode: "Modo de 1 Palo / 2 Palos",
        .helpShortcutAutocomplete: "Autocompletar",
        .helpShortcutDealDraw: "Repartir / Robar",
        .helpShortcutHoldCard12345: "Retener Carta 1, 2, 3, 4, 5",
        .helpShortcut12345: "1, 2, 3, 4, 5",
        .helpShortcutHoldAllCards: "Retener Todas las Cartas",
        .helpShortcutBetMaxDeal: "Apuesta Máxima y Repartir",
        .helpShortcutDealBuyIn: "Repartir / Comprar Fichas",
        .helpShortcutHit: "Pedir",
        .helpShortcutStand: "Plantarse",
        .helpShortcutDoubleDown: "Doblar",
        .ruleNamePollination: "Polinización",
        .ruleNameSmokedOut: "Ahumado",
        .ruleNameSymmetry: "Simetría",
        .ruleNameMathBee: "Abeja Matemática",
        .ruleNameQueensFall: "Caída de la Reina",
        .ruleNameInversion: "Inversión",
        .ruleNameClearSkies: "Cielos Despejados",
        .ruleNameHierarchy: "Jerarquía",
        .ruleNameFrenzy: "Frenesí",
        .ruleExplanationSame: "Si 2+ estadísticas de vecinos en contacto coinciden con las estadísticas de cara de tu carta, todos los vecinos coincidentes se capturan simultáneamente.",
        .ruleExplanationPlus: "Si la suma de (tu estadística + la estadística del vecino) iguala el mismo total en 2+ vecinos, todas las cartas involucradas son capturadas.",
        .ruleExplanationFallenAce: "¡Una carta con una estadística de 1 atacando a un 10 (\"A\") siempre lo captura! Si Inversión también está activa, esto se voltea: un 10 (\"A\") captura a un 1 en su lugar.",
        .ruleExplanationAscensionGeneric: "Otorga +1 a las estadísticas de todas las cartas que coincidan con palos seleccionados aleatoriamente a medida que entren más de ese palo en el tablero.",
        .ruleExplanationDescensionGeneric: "Inflige -1 a las estadísticas de todas las cartas que coincidan con palos seleccionados aleatoriamente a medida que entren más de ese palo en el tablero.",
        .ruleExplanationOrder: "Te obliga a jugar las cartas en la secuencia exacta del mazo.",
        .ruleExplanationAllOpen: "Las manos de ambos jugadores son completamente visibles.",
        .ruleExplanationThreeOpen: "Tres cartas seleccionadas al azar de la mano de cada jugador son visibles.",
        .ruleExplanationBombShelter: "La primera carta jugada de cada jugador permanece boca abajo durante 3 turnos antes de voltearse automáticamente.",
        .ruleExplanationSuddenDeath: "Si la partida termina en empate, comienza una revancha inmediatamente.",
        .ruleExplanationSwap: "Antes de la partida, una carta de tu mano se intercambia aleatoriamente con una del oponente.",
        .difficultyEasyRawvalue: "Fácil",
        .difficultyMediumRawvalue: "Medio",
        .difficultyHardRawvalue: "Difícil",
        .gamemodeBeecellDisplay: "Beecell",
        .rouletteColonPrefix: "Ruleta: ",
        .rulesRandomizedAtStart: "Las reglas se seleccionan al azar al inicio de la partida.",
        .ruleNameColonFmt: "%@: ",
        .banColumnHeader: "¿Vetar?",
        .playColumnHeader: "Jugar",
        .matchRulesHintWin: "Selecciona hasta 4 reglas. Déjalo vacío para que la ruleta decida las reglas de cada partida.",
        .banRemovesRuleHint: "Vetar elimina una regla por completo del grupo de la ruleta.",
        .opponentLabelColon: "Oponente:",
        .saveNewThemeEllipsisWin: "Guardar Nuevo Tema…",
        .firstMovePlayer: "¡Primer Movimiento: Jugador!",
        .firstMoveOpponentFmt: "¡Primer Movimiento: %@!",
        .helpNoStressModeTitle: "🧘 Modo Sin Estrés",
        .helpGuideContentsHeader: "CONTENIDO",
        .helpGuideWindowTitle: "Guía de Ayuda",
        .helpThemesSettingsIndexLabel: "Temas y Configuración",
        .helpShortcutClearAllHolds: "Soltar Todas las Cartas",
        .settingsHeaderVideopoker: "VIDEO POKER",
        .handRoyalFlush: "Escalera Real",
        .swarmRevealPlayerHiveSwarm: "Tu Enjambre de Colmena",
        .swarmRevealPlayerUnleashed: "¡Tu Enjambre se Desata!",
        .swarmRevealPlayerAwakens: "¡Tu Enjambre Despierta!",
        .swarmRevealPlayerBuzzing: "¡Tu Colmena Zumba en Acción!",
        .swarmRevealOpponentHiveSwarmFmt: "Enjambre de Colmena de %@",
        .swarmRevealOpponentUnleashedFmt: "¡El Enjambre de %@ se Desata!",
        .swarmRevealOpponentAwakensFmt: "¡El Enjambre de %@ Despierta!",
        .swarmRevealOpponentBuzzingFmt: "¡La Colmena de %@ Zumba en Acción!",
        .bannerHiveMindFmt: "¡MENTE COLMENA x%d!",
        .gameModeSectionHeader: "Modo de Juego",
        .savedThemesHeader: "Temas Guardados",
        .doubleClickCardOrBackgroundTooltip: "Haz doble clic en la carta o el fondo para ajustarlo",
        .deleteBackgroundConfirmBody: "¿Seguro que quieres eliminar este fondo personalizado? Esto no se puede deshacer.",
        .saveNewThemeTitle: "Guardar Nuevo Tema",
        .enterThemeNamePrompt: "Introduce un nombre para este tema:",
        .tapTileUploadArtHint: "Toca un mosaico para subir arte. Toca de nuevo para ajustar.",
        .suitNameSpadesPlain: "Picas",
        .suitNameHeartsPlain: "Corazones",
        .suitNameDiamondsPlain: "Diamantes",
        .suitNameClubsPlain: "Tréboles",
        .aboutDownloadingUpdate: "Descargando actualización…",
        .aboutDownloadingUpdatePctFmt: "Descargando actualización… %d%%",
        .aboutUpdateDownloadFailed: "No se pudo descargar la actualización.",
        .installAndRestart: "Instalar y Reiniciar",
        .addBackgroundTitle: "Añadir Fondo",
        .editBackgroundTitle: "Editar Fondo",
        .cardBackFillNote: "Este reverso de carta llena la carta automáticamente\ny no usa ajustes de posición.",
        .btnDealDHotkey: "Repartir  [D]",
        .btnDrawDHotkey: "Robar  [D]",
        .removeFromDeckContextMenu: "¿Quitar del mazo?",
        .starCountFilterFmt: "%d Estrella%@",
        .noCardsMatchFilter: "Ninguna carta coincide con este filtro.",
        .youLose: "Perdiste",
        .drawSuddenDeathFmt: "¡Empate - %@!",
        .resultDealerWins: "Gana el Repartidor",
        .resultHandWinFmt: "Mano %d: Gana",
        .resultHandLossFmt: "Mano %d: Pierde",
        .resultHandPushFmt: "Mano %d: Empate",
        .resultHandBustFmt: "Mano %d: Se pasó",
        .newMatchConfirmTitle: "¿Empezar un nuevo partido? Tu partido actual terminará.",
        .rematchConfirmTitle: "¿Revancha? Tu partido actual terminará.",
        .menuTabGameSelection: "Selección de Juego",
        .menuHeaderTitle: "Menú",
        .closeMenuA11y: "Cerrar menú",
        .menuSectionGame: "Juego",
        .menuSectionTheme: "Tema",
        .menuSectionCardBack: "Reverso de Carta",
        .menuSectionBackground: "Fondo",
        .backgroundNoneOption: "Ninguno",
        .removeCardBackAlertTitle: "¿Quitar Reverso de Carta?",
        .removeBackgroundAlertTitle: "¿Quitar Fondo?",
        .removeImportedImageBody: "Esto elimina la imagen importada. No se puede deshacer.",
        .statisticsNavRow: "Estadísticas",
        .howToPlayNavRow: "Cómo Jugar",
        .faceCardArtNavRow: "Arte de Carta",
        .touchNewDealLabel: "Nuevo",
        .touchUndoLastMoveLabel: "Deshacer Última Jugada",
        .touchDealA11y: "Repartir",
        .touchCompletedRunsA11y: "Series completadas",
        .touchDecksPickerLabel: "Mazos",
        .touchSingleDeckOption: "Mazo Sencillo",
        .touchDoubleDeckOption: "Doble Mazo",
        .touchSuitsPickerLabel: "Palos",
        .touchBetMaxButton: "Máx",
        .touchSettingsUnlockBetweenHands: "La configuración se desbloquea entre manos.",
        .touchSettingsUnlockHandEnds: "La configuración se desbloquea cuando termina la mano.",
        .touchHandsDealtStat: "Manos Repartidas",
        .touchSessionCreditsStat: "Créditos de Sesión",
        .touchHandLabelFmt: "MANO %d",
        .touchYouLabel: "TÚ",
        .touchBustSuffix: " SE PASÓ",
        .touchResultWin: "GANA",
        .touchResultLoss: "PIERDE",
        .touchResultPush: "EMPATE",
        .touchResultBlackjack: "¡BLACKJACK!",
        .touchResultBust: "SE PASÓ",
        .touchActionHit: "Pedir",
        .touchActionStand: "Plantarse",
        .touchActionDouble: "Doblar",
        .touchActionSplit: "Dividir",
        .touchResetPositionButton: "Restablecer Posición",
        .touchAddCardBackTitle: "Añadir Reverso de Carta",
        .stealInstructionTap: "Toca dos veces la carta capturada de un oponente\nen el tablero para robarla.",
    ]
}
