// GENERATED FILE — do not hand-edit.
// Regenerate via `python3 tools/generate_localization.py` from
// Honeycomb_Localization.xlsx.

enum StringsEnglish {
    static let table: [StringKey: String] = [
        .newGame: "New Game",
        .restart: "Restart",
        .undo: "Undo",
        .cancel: "Cancel",
        .ok: "OK",
        .done: "Done",
        .hint: "Hint",
        .options: "Options",
        .preferences: "Preferences",
        .viewStats: "View Stats",
        .visualThemes: "Visual Themes",
        .visualThemesSubtitle: "Felt, card back, face card art, colors",
        .language: "Language",
        .languageEnglish: "English",
        .languageSpanish: "Español",
        .resetStatisticsTitle: "Reset Statistics?",
        .resetStatisticsBody: "This will permanently clear all statistics for the current game. This cannot be undone.",
        .reset: "Reset",
        .scoreLabel: "SCORE",
        .movesLabel: "MOVES",
        .timeLabel: "TIME",
        .save: "Save",
        .delete: "Delete",
        .remove: "Remove",
        .add: "Add…",
        .addShort: "Add",
        .edit: "Edit",
        .back: "Back",
        .close: "Close",
        .errorTitle: "Error",
        .yes: "Yes",
        .soundEffects: "Sound Effects",
        .soundShort: "Sound",
        .noStressMode: "No Stress Mode",
        .honeyMode: "Honey Mode (Flavor)",
        .hideHintButton: "Hide Hint Button",
        .manuallyDismissBanners: "Manually Dismiss Banners",
        .vegasScoring: "Vegas Scoring",
        .vegasScoringMode: "Vegas Scoring Mode",
        .alwaysOnTop: "Always on Top",
        .timed: "Timed",
        .startingCreditsFmt: "Starting Credits: %d",
        .dealerLabel: "DEALER",
        .playerLabel: "PLAYER",
        .vsDivider: "VS",
        .youWin: "You Win!",
        .gameOver: "Game Over",
        .noMovesRemaining: "No moves remaining.",
        .restartGame: "Restart Game",
        .victoryGuaranteed: "Victory is guaranteed!",
        .autocompleteGame: "Autocomplete Game",
        .playAgain: "Play Again",
        .noHintsAvailable: "Sorry! No hints available.",
        .newGameConfirmTitle: "Start a new game? Your current game will end.",
        .scoreFmt: "Score: %@",
        .bankrollFmt: "Bankroll: %@",
        .gamesPlayed: "Games Played",
        .gamesWon: "Games Won",
        .highScore: "High Score",
        .winPercentage: "Win Percentage",
        .currentStreak: "Current Streak",
        .longestStreak: "Longest Streak",
        .avgWinningTime: "Avg Winning Time",
        .fastestWin: "Fastest Win",
        .resetStats: "Reset Stats",
        .resetStatisticsBodyGeneric: "This will permanently clear all statistics. This cannot be undone.",
        .handsPlayed: "Hands Played",
        .handsWon: "Hands Won",
        .winRate: "Win Rate",
        .totalWagered: "Total Wagered",
        .totalPaid: "Total Paid",
        .biggestPay: "Biggest Pay",
        .rtpStat: "RTP",
        .rebuysStat: "Rebuys",
        .royalFlushes: "Royal Flushes",
        .deckCount1: "1-Deck",
        .deckCount2: "2-Decks",
        .suitCount1: "1 Suit",
        .suitCount2: "2 Suits",
        .suitCount4: "4 Suits",
        .manageDecks: "Manage Decks",
        .rematch: "Rematch",
        .newMatch: "New Match",
        .notTodayPartner: "Not today, partner!",
        .cardAddedToBank: "Card added to card bank.",
        .cardBankFullLine1: "Your card bank is full. Start over in manage decks to steal again.",
        .cardBankFullLine2: "All of their secrets, yours. There's nothing left to steal.",
        .obtainedAllCardsFmt: "You have obtained all cards from %@'s hand.",
        .rematchToTakeAnother: "Rematch to take another.",
        .stealProtectionLine: "The hive takes pity on you — a rare card finds its way home.",
        .stealCard: "Steal a Card",
        .confirmStealTitle: "Are you sure you want to steal this card?",
        .stealInstruction: "Double-click a captured opponent's card\non the board to steal it.",
        .sillyBeeWarning: "You cannot blacklist every game, silly bee.",
        .startOver: "Start Over",
        .startOverTitle: "Start Over?",
        .startOverBody: "Want a fresh start? Starting over clears your saved decks and card bank, then reseeds the game with a whole new set of cards.",
        .startOverAlertBody: "Starting over reseeds the game with an entirely new set of cards. All saved decks and card bank progress. This can't be undone.",
        .emptySlotFmt: "Empty Slot %d",
        .deckActiveBadge: "Active",
        .deckSetActive: "Set Active",
        .deckCreate: "Create",
        .allStarsFilter: "All Stars",
        .starCountFmt: "%d★",
        .allSuitsFilter: "All Suits",
        .suitSpades: "♠ Spades",
        .suitHearts: "♥ Hearts",
        .suitDiamonds: "♦ Diamonds",
        .suitClubs: "♣ Clubs",
        .favoritesFilter: "Favorites",
        .clearFilters: "Clear",
        .deckBuilderTitle: "Deck Builder",
        .deckRulesHint: "Maximum one 5★ and one 4★ card per deck. Two 4★ cards can be used without a 5★.",
        .errTooMany5star: "A deck can never contain more than one 5★ card.",
        .err5star4starCombo: "If you have a 5★ card, you can only have one 4★ card.",
        .errTooMany4star: "A deck can never contain more than two 4★ cards.",
        .errNameTooLong: "Deck name cannot exceed 20 characters.",
        .cardBankCountFmt: "CARD BANK (%d of %d)",
        .yourDeckCountFmt: "Your Deck (%d/5) — Tap to Remove",
        .cardBankTapToAdd: "Card Bank — Tap to Add",
        .dealButton: "Deal",
        .rebuyButton: "Rebuy",
        .buyInButton: "Buy In",
        .hitSpaceToDeal: "Hit Space to Deal",
        .holdAll: "Hold All",
        .betMax: "Bet Max",
        .scoreYouFmt: "You %d",
        .scoreDealerFmt: "%@ %d",
        .appNavigationTitle: "Honeycomb Card Suite",
        .resetDefaultCardBacks: "Reset Default Card Backs",
        .stayOnTop: "Stay on Top",
        .helpKlondike: "Klondike Solitaire Help",
        .helpFreecell: "Freecell Help",
        .helpSpider: "Spider Solitaire Help",
        .helpVideopoker: "Video Poker Help",
        .helpBlackjack: "Video Blackjack Help",
        .helpHoneycomb: "Honeycomb Help",
        .helpThemes: "Themes Help",
        .aboutHoneycomb: "About Honeycomb",
        .appName: "Honeycomb",
        .cardSuiteLabel: "CARD SUITE",
        .versionFmt: "Version %@",
        .copyrightNotice: "© 2026 Leahbee. All rights reserved.",
        .dedication: "For Rhinestone.",
        .checkForUpdates: "Check for Updates…",
        .checkingForUpdates: "Checking for updates…",
        .upToDate: "You're up to date.",
        .checkAgain: "Check Again",
        .updateCheckFailed: "Couldn't check for updates. Check your internet connection.",
        .tryAgain: "Try Again",
        .newerVersionAvailableFmt: "Version %@ is available.",
        .viewRelease: "View Release",
        .statusBankroll: "BANKROLL",
        .stockExhausted: "Stock\nExhausted",
        .finalBankrollFmt: "Final bankroll: %@",
        .autocompleteBodyKlondike: "All remaining cards can be moved to foundations.",
        .autocompleteBodyOther: "All remaining cards can be sorted into foundations.",
        .hotkeyLegendKlondike: "Arrows=Move Cursor   Space/Return=Select or Move   D=Draw   F=Auto-Foundation   A=Autocomplete   Esc=Clear Cursor",
        .hotkeyLegendBeecell: "Arrows=Move Cursor   Space/Return=Select or Move   C=Free Cell   F=Auto-Foundation   A=Autocomplete   Esc=Clear Cursor",
        .hotkeyLegendSpider: "Arrows=Move Cursor   Space/Return=Select or Move   D=Deal   A=Autocomplete   Esc=Clear Cursor",
        .hotkeyLegendBlackjack: "Space=Deal   H=Hit   S=Stand   D=Double Down   P=Split",
        .hotkeyLegendVideopoker: "Space/Enter/D=Deal or Draw   1-5=Toggle Hold   H=Hold All   C=Clear   M=Bet Max",
        .restartConfirmTitle: "Restart this game from the beginning?",
        .newGameConfirmTitleShort: "Start a new game?",
        .winSummaryWithTimeFmt: "%@ | Time: %@",
        .drawModeLabel: "Draw Mode:",
        .drawOne: "Draw One",
        .drawThree: "Draw Three",
        .faceCardsTitle: "Face Cards",
        .cardColorsTitle: "Card Colors",
        .themesPanelTitle: "Themes",
        .addCustomCardArtHeading: "Add Custom Card Art",
        .jpgPngAcceptedSuffix: "(.jpg or .png accepted):",
        .doubleClickAdjustBackgroundTooltip: "Double-click to adjust the background",
        .clickAdjustCardBackTooltip: "Click to adjust the card back",
        .customFeltColorLabel: "Custom Felt Color:",
        .customizeFaceCardsTitle: "Customize Face Cards for Theme",
        .customizeFaceCardsSubtitle: "16 slots — Aces, Jacks, Queens, Kings per suit",
        .customCardColorsTitle: "Custom Card Colors for Theme",
        .customCardColorsSubtitleMac: "Background, outline, suit text, hint highlight",
        .customCardColorsSubtitleWin: "Background, outline, text, hint highlight",
        .livePreviewNotice: "Live preview — edits below apply to these cards immediately.",
        .backgroundLabel: "Background:",
        .feltGreen: "Felt Green",
        .feltCrimson: "Crimson",
        .feltRoyalBlue: "Royal Blue",
        .feltCharcoal: "Charcoal",
        .feltDesert: "Desert",
        .feltCustomColor: "Custom Felt Color",
        .addCustomBackgroundOption: "Add Custom Background…",
        .feltVignetteToggle: "Felt Vignette",
        .deleteCurrentWallpaper: "Delete Current Wallpaper",
        .couldNotSaveBackgroundError: "Could not save the background. The image may be corrupt or the disk is full.",
        .deleteBackgroundTitle: "Delete Background",
        .deleteBackgroundBody: "Are you sure you want to delete this background?",
        .couldNotLoadSelectedImageFileError: "Could not load the selected image file.",
        .fileMustBeJpgPngError: "File must be .jpg or .png!",
        .imageTooLargeTitle: "Image Too Large",
        .imageTooLargeMessage: "That image is larger than 25 MB. Please choose a smaller file.",
        .backgroundInvalidFormatWin: "Selected file is not a valid PNG or JPEG image.",
        .editCustomBackgroundTitle: "Edit Custom Background",
        .backgroundNameLabel: "Background Name:",
        .backgroundNamePlaceholder: "e.g. My Desk",
        .horizontalPositionLabel: "Horizontal Position:",
        .pxOffsetFmt: "%.0f px",
        .verticalPositionLabel: "Vertical Position:",
        .scaleFactorLabel: "Scale Factor:",
        .scaleFmt: "%.2fx",
        .nameEmptyOrExistsError: "Name cannot be empty or already exist!",
        .editCardBackTitle: "Edit Card Back",
        .editCustomCardArtTitle: "Edit Custom Card Art",
        .cardBackNameLabel: "Card Back Name:",
        .cardBackNamePlaceholder: "e.g. My Dog",
        .addNameToSaveError: "Add a name to save.",
        .deleteDeckTooltip: "Delete deck",
        .deleteCardBackTitle: "Delete Card Back",
        .deleteNamedCardBackConfirmFmt: "Are you sure you want to delete \"%@\"?",
        .deleteCardBackBody: "Are you sure you want to delete this custom card back? This cannot be undone.",
        .cardDeckHeading: "Card Deck",
        .jpgPngGifAcceptedSuffix: "(.jpg, .png, or .gif accepted):",
        .addCustomDeck: "Add Custom…",
        .cardBackLastRemaining: "At least one card deck design must remain — you can't delete the last one.",
        .customCardColorHeading: "Custom Card Color",
        .customCardColorsPanelTitle: "Custom Card Colors",
        .resetCardColors: "Reset Card Colors",
        .resetCardColorsConfirmBody: "Are you sure you want to reset the card colors to default?",
        .cardBackgroundLabel: "Card Background",
        .cardOutlineLabel: "Card Outline",
        .blackSuitTextLabel: "Black Suit Text",
        .redSuitTextLabel: "Red Suit Text",
        .hintHighlightLabel: "Hint Highlight",
        .editFaceCardArtTitleFmt: "Edit %@%@ Art",
        .scaleShortLabel: "Scale",
        .horizontalShortLabel: "Horizontal",
        .verticalShortLabel: "Vertical",
        .removeArtTooltip: "Remove art",
        .removeArtTitle: "Remove Art",
        .removeArtConfirmBody: "Remove the custom art for this slot?",
        .fileMustBeJpgPngGifError: "File must be .jpg, .png, or .gif.",
        .couldNotLoadSelectedImageError: "Could not load the selected image.",
        .couldNotReadImageDataError: "Could not read image data.",
        .toggleGameModeLabel: "Game Mode:",
        .option1deck: "Standard (1-Deck)",
        .option2deck: "Two Decks (2-Decks)",
        .freecellStatisticsFmt: "Freecell Statistics (%@)",
        .gamesPlayedColon: "Games Played:",
        .gamesWonColon: "Games Won:",
        .highScoreColon: "High Score:",
        .winPercentageColon: "Win Percentage:",
        .currentStreakColon: "Current Streak:",
        .longestStreakColon: "Longest Streak:",
        .avgWinningTimeColon: "Avg Winning Time:",
        .fastestWinColon: "Fastest Win:",
        .resetBankrollButton: "Reset Bankroll",
        .creditsLabel: "CREDITS",
        .betLabel: "BET",
        .handsLabel: "HANDS",
        .resultHeadlineBlackjack: "Blackjack!",
        .resultHeadlinePush: "Push",
        .resultSubPush: "Bets returned",
        .resultHeadlineBust: "Bust!",
        .resultSubNetPositiveFmt: "+%d credits",
        .resultSubNetNegativeFmt: "%d credits",
        .resultSubEven: "Even",
        .resultDealerValueFmt: "Dealer: %d",
        .resultPlayerValueFmt: "Player: %d",
        .streakText5plusFmt: "*** %d WIN STREAK ***",
        .streakText3to4Fmt: "** %d WIN STREAK **",
        .streakText2Fmt: "%d wins in a row!",
        .btnClearBet: "CLEAR BET",
        .btnClearBetWin: "Clear Bet",
        .btnDealSpace: "DEAL  [Space]",
        .btnDealSpaceWin: "Deal  [Space]",
        .btnRebuyMac: "REBUY",
        .btnHit: "HIT  [H]",
        .btnHitWin: "Hit  [H]",
        .btnStand: "STAND  [S]",
        .btnStandWin: "Stand  [S]",
        .btnDouble: "DOUBLE  [D]",
        .btnDoubleWin: "Double  [D]",
        .btnSplit: "SPLIT  [P]",
        .btnSplitWin: "Split  [P]",
        .keyHintRowWin: "Space/Enter=Deal   H=Hit   S=Stand   D=Double   P=Split",
        .chipAmountFmt: "+%d",
        .chip1: "1",
        .chip5: "5",
        .chip10: "10",
        .chip25: "25",
        .chip2x: "2X",
        .blackjackStatistics: "Blackjack Statistics",
        .statHandsLost: "Hands Lost",
        .statPushes: "Pushes",
        .statBlackjacks: "Blackjacks",
        .statCurStreakShort: "Cur. Streak",
        .statBestStreak: "Best Streak",
        .msgResetStatsBlackjack: "This will permanently clear all Blackjack statistics. This cannot be undone.",
        .emptyColumnDrawToast: "You must fill all empty tableau slots before drawing.",
        .pickerSuitsLabel: "Suits:",
        .optionSuits1: "1 (Spades)",
        .optionSuits2: "2 (♠♥)",
        .optionSuits4: "4 (Standard)",
        .spiderStatisticsFmt: "Spider Statistics (%d %@)",
        .labelSuitSingular: "Suit",
        .labelSuitPlural: "Suits",
        .statAverageWinTime: "Average Win Time",
        .noTimePlaceholder: "--",
        .betHandLabel: "BET/HAND",
        .totalBetLabel: "TOTAL BET",
        .payTableMaxCol: "MAX",
        .resultHandNameFmt: "%@!",
        .resultCreditsWonFmt: "+%d Credits",
        .resultCreditsLostFmt: "-%d credits",
        .minusCreditsSuffix: "credits",
        .btnBetMinus: "-",
        .btnBetMaxMac: "BET MAX  [M]",
        .btnBetPlus: "+",
        .btnHoldAllMac: "HOLD ALL  [H]",
        .btnHoldAllWin: "Hold All  [H]",
        .btnClearHoldsMac: "CLEAR  [C]",
        .btnClearHoldsWin: "Clear  [Q]",
        .btnDraw: "DRAW",
        .btnDrawWinMinus: "− Bet",
        .btnDrawWinPlus: "+ Bet",
        .tapHoldDrawHint: "Tap cards to hold, then Draw",
        .heldLabel: "HELD",
        .payoutResultFmt: "%@  +%d",
        .pickerVariantLabel: "Variant:",
        .pickerPlaymodeLabel: "Play Mode:",
        .pickerDefaultBetLabel: "Default Bet:",
        .optionCoinCountFmt: "%d coin%@",
        .variantJacksOrBetter: "Jacks or Better",
        .variantDeucesWild: "Deuces Wild",
        .variantBonusPoker: "Bonus Poker",
        .videoPokerStatistics: "Video Poker Statistics",
        .toolbarStartMatch: "Start Match",
        .toolbarQuitMatch: "Quit Match",
        .toolbarRules: "Rules",
        .honeycombRulesTitle: "Honeycomb Rules",
        .statusYouLabel: "You",
        .rulesBannerTitle: "Rules:",
        .ruleLineNormal: "Normal",
        .ruleLineRoulette: "Roulette",
        .ruleLineSuitFmt: "%@ Suit: %@",
        .handLabelYou: "YOU",
        .quitButton: "Quit",
        .startButton: "Start",
        .noHintsBanner: "No hints for this one!",
        .dismissA11y: "Dismiss",
        .settingsHeader: "HONEYCOMB",
        .opponentPickerLabel: "Opponent",
        .forceNormalRulesToggle: "Force Normal Rules",
        .toggleNormalModeMac: "Normal Mode (Force Zero Rules)",
        .rulesColumnTitle: "Game Rules",
        .matchRulesHint: "Pick up to 4 rules to lock in, or leave empty to let roulette decide. Ban a rule to keep it out entirely. Hover over a rule to see its explanation.",
        .normalModeBanItem: "Normal Mode",
        .settingsUnlockNote: "Settings unlock when the match ends.",
        .statsSheetTitle: "Honeycomb Stats",
        .honeycombStatistics: "Honeycomb Statistics",
        .statMatchesPlayed: "Matches Played",
        .statMatchesWon: "Matches Won",
        .statMatchesLost: "Matches Lost",
        .statMatchesDrawn: "Matches Drawn",
        .statCardsCaptured: "Cards Captured",
        .statCardsStolen: "Cards Stolen",
        .statCurrentWinStreak: "Current Win Streak",
        .statLongestWinStreak: "Longest Win Streak",
        .statFlawlessVictoriesIos: "Flawless Victories",
        .statFlawlessVictoriesMac: "Flawless Victories (10-0 Sweep)",
        .statSamePlusTriggers: "Same/Plus Triggers",
        .statWinsByDifficultySection: "Wins by Difficulty",
        .statBabyBee: "Baby Bee",
        .statHoneyBee: "Honey Bee",
        .statQueenBee: "Queen Bee",
        .statKillerBee: "Killer Bee",
        .statBabyBeeWins: "Baby Bee Wins",
        .statHoneyBeeWins: "Honey Bee Wins",
        .statQueenBeeWins: "Queen Bee Wins",
        .statKillerBeeWins: "Killer Bee Wins",
        .statSwarmsToDeath: "Most Swarms to the Death",
        .statTotalCardsFlipped: "Total Cards Flipped",
        .statQueensFalls: "Queen's Falls",
        .statHiveMindsTriggered: "Symmetry/Math Bee Hive Minds Triggered",
        .statTimesStartedOver: "Times Started Over",
        .statCardsUnlockedLabel: "Cards Unlocked",
        .statCardsUnlockedValueFmt: "%d/%d (%@)",
        .statSuitUnlockedFmt: "%@ Unlocked",
        .statStarUnlockedFmt: "%d★ Unlocked",
        .tieResult: "Tie!",
        .finalScoreFmt: "Final Score: {0} - {1}",
        .sheetTitleMac: "Saved Decks & Card Bank",
        .tabSavedDecks: "Saved Decks",
        .tabCardBank: "Card Bank",
        .statSearchHint: "Freeform search: type a value onto the card to filter the bank.",
        .savedDecksHeader: "SAVED DECKS",
        .deckNamePlaceholder: "Deck Name (Max 20 chars)",
        .deckNamePlaceholderIos: "Deck Name (max 20 chars)",
        .enterDeckNameHint: "Enter a deck name to save.",
        .contextRemoveFromDeck: "Remove from deck?",
        .btnSaveDeck: "Save Deck",
        .deckSlotDefaultNameFmt: "Deck %d",
        .klondikeStatisticsTitle: "Klondike Statistics",
        .vegasBankrollLabel: "Vegas Bankroll:",
        .handHighCard: "High Card",
        .handOnePair: "One Pair",
        .handTwoPair: "Two Pair",
        .handThreeOfAKind: "Three of a Kind",
        .handStraightFlush: "Straight Flush",
        .handFlush: "Flush",
        .handStraight: "Straight",
        .handFourOfAKind: "Four of a Kind",
        .handFullHouse: "Full House",
        .handFiveOfAKind: "Five of a Kind",
        .handFourAces: "Four Aces",
        .handFour2s4s: "Four 2s–4s",
        .handFourDeuces: "Four Deuces",
        .handNaturalRoyalFlush: "Natural Royal Flush",
        .handWildRoyalFlush: "Wild Royal Flush",
        .handNoWin: "No Win",
        .difficultyUltraHardRawvalue: "Ultra Hard",
        .ruleNameCappedBrood: "Capped Brood",
        .ruleNameNectarExchange: "Nectar Exchange",
        .ruleNameScoutingParty: "Scouting Party",
        .ruleNameSwarmToTheDeath: "Swarm to the Death",
        .ruleExplanationChaos: "Randomly mandates which card must be played each turn.",
        .ruleExplanationReverse: "Inverts all comparisons—lower stats beat higher stats.",
        .normalModeBanListTooltip: "Forces a match with no active rules, skipping roulette.",
        .gamemodeKlondikeDisplay: "Klondike Solibee",
        .gamemodeSpiderDisplay: "Spider Solibee",
        .playmodeSingle: "Single Play",
        .playmodeTriple: "Triple Play",
        .gameSelectionLabel: "Game Selection",
        .hintRecycleWasteToStock: "Recycle Waste pile to Stock.",
        .themeNameFieldPlaceholder: "Theme name",
        .themeNameEmptyError: "Theme name can't be empty.",
        .themeNameExistsErrorFmt: "A theme named \"%@\" already exists.",
        .renameThemeTitle: "Rename Theme",
        .saveAsNewTheme: "Save as New Theme",
        .noSavedThemesYet: "No saved themes yet.",
        .deleteThemeTitle: "Delete Theme",
        .applyThemeButton: "Apply",
        .deleteThemeConfirmFmt: "Delete \"%@\"? This cannot be undone.",
        .helpHoneycombSubtitle: "A tactical 3×3 grid card battle inspired by Triple Triad.",
        .helpCoreGameplayMechanicsTitle: "🎮 Core Gameplay & Mechanics",
        .helpHowToPlayVariantsTitle: "🎮 How to Play & Variants",
        .helpStrategyProTipsTitle: "💡 Strategy & Pro Tips",
        .helpOverviewObjectiveTitle: "📌 Overview & Objective",
        .helpControlsShortcutsTitle: "⌨️ Controls & Shortcuts",
        .helpShortcutClickDragTap: "Click & Drag or Tap Card → Tap Cell",
        .helpShortcutNavigateSelect: "Navigate / Select",
        .helpShortcutSelectPlaceCard: "Select / Place Card",
        .helpShortcutSelectPlaceSequence: "Select / Place Sequence",
        .helpShortcutShowBestAiMove: "Show Best AI Move",
        .helpShortcutSplitPairs: "Split Pairs",
        .helpShortcutArrowKeys: "Arrow Keys",
        .helpShortcutCQ: "C / Q",
        .helpShortcutSpaceEnter: "Space / Enter",
        .helpShortcutCmdNR: "⌘N / ⌘R",
        .helpShortcutCmdZ: "⌘Z",
        .helpBeecellTitle: "Freecell (Beecell)",
        .helpKlondikeObjective: "Move all 52 cards to the four Foundation piles, organized by suit from Ace (lowest) to King (highest).",
        .helpKlondikeLayout: "• Tableau (7 Columns): Dealt from left to right with 1 to 7 cards respectively. Only the top card in each column is face-up.\n• Stock Pile (Top-Left): Contains the remaining 24 face-down cards.\n• Waste Pile (Next to Stock): Holds cards drawn from the stock.\n• Foundations (Top-Right): Four empty slots reserved for completing each suit.",
        .helpKlondikeRules: "• Tableau Building: Stack cards in descending rank with alternating colors (e.g., a red 6 on a black 7). You may move a single card or an entire face-up sequence to another column.\n• Empty Columns: Only a King (or a sequence starting with a King) may be placed in an empty tableau column.\n• Stock & Waste:\n  – Draw 1 Mode: Clicking the stock reveals 1 card to the waste.\n  – Draw 3 Mode: Reveals 3 cards; only the top card of the waste is playable. Once played, the next card in the 3-card batch becomes available.\n• Scoring Modes:\n  – Standard: Flip face-down card (+5 pts) · Waste to Tableau (+5 pts) · Waste/Tableau to Foundation (+10 pts) · Foundation back to Tableau (−15 pts).\n  – Vegas: Start with a debt of −$52. Earn +$5 for every card moved to a foundation. Draw 1 permits only 1 pass through the stock; Draw 3 allows 3 passes (2 redeals).",
        .helpKlondikeStrategy: "1. Prioritize Face-Down Cards: Always prioritize moves that reveal hidden cards in the longest tableau columns.\n2. Keep Columns Open: Don't clear a tableau column unless you already have a King ready to occupy it.\n3. Delay Foundation Moves: Avoid rushing cards into the foundation early if those cards might be needed to build lower sequences in the tableau.",
        .helpKlondikeNoStress: "Enabling No Stress Mode in Options disables the game timer completely.",
        .helpBeecellObjective: "Move all 52 cards to the four Foundation piles, built up by suit from Ace to King.",
        .helpBeecellLayout: "• Tableau (8 Columns): All 52 cards are dealt face-up at the start (4 columns of 7 cards, 4 columns of 6 cards).\n• Free Cells (Top-Left): Four temporary storage slots.\n• Foundations (Top-Right): Four suit build-up piles.",
        .helpBeecellRules: "• Tableau Building: Stack cards in descending rank and alternating colors.\n• Free Cell Storage: Each free cell can hold exactly 1 card at a time.\n• Multi-Card Movement Capacity: You can move a face-up card sequence in a single action. The maximum number of cards you can move at once is calculated as: (Free Cells Available + 1) × 2^(Empty Tableau Columns).\n• Empty Columns: Any single card or valid sequence can be moved into an empty tableau column.",
        .helpBeecellStrategy: "1. Protect Your Free Cells: Treat free cells as temporary maneuvering space. Avoid filling all four free cells simultaneously, as it drastically reduces your sequence-moving capacity.\n2. Uncover Low Cards Early: Focus on freeing up Aces and 2s buried at the bottom of columns.\n3. Empty Columns are Gold: An empty column doubles your movement capacity and acts as an unrestricted free cell.",
        .helpSpiderObjective: "Assemble eight complete same-suit sequences from King down to Ace within the tableau. Each completed 13-card sequence is automatically removed to the foundation.",
        .helpSpiderLayout: "• Tableau (10 Columns): 54 cards dealt across 10 columns (first 4 get 6 cards; last 6 get 5 cards). Only the top card of each column is face-up.\n• Stock (Bottom/Top): 50 remaining cards arranged in 5 extra deals of 10 cards each.",
        .helpSpiderRules: "• Difficulty Modes:\n  – 1-Suit (Easy): All 104 cards are Spades.\n  – 2-Suits (Medium): 52 Spades and 52 Hearts.\n  – 4-Suits (Hard): All four standard suits are used.\n• Tableau Building: Stack cards in descending rank regardless of suit (e.g., a 7 of Hearts can sit on an 8 of Spades). Crucial Exception: You may only move a multi-card sequence if all cards in that sequence share the same suit.\n• Stock Deals: Click the stock to deal 1 card onto every tableau column. Requirement: Every column must contain at least 1 card before you can deal from the stock.",
        .helpSpiderStrategy: "1. Same-Suit Over Mixed-Suit: Always prefer building same-suit runs. Mixed-suit stacks lock up your cards and cannot be moved together.\n2. Empty Columns First: Empty columns allow you to isolate mixed-suit stacks and re-organize them into clean same-suit runs.\n3. Delay Dealing: Exhaust every possible move on the board before clicking the stock.",
        .helpVideopokerObjective: "Draw a 5-card hand that matches a qualifying entry on the pay table to earn credit multipliers.",
        .helpVideopokerHowToPlay: "1. Betting: Select 1 to 5 coins. Press Bet Max (M) to bet 5 coins and immediately deal. (Note: The 800× Royal Flush jackpot is only awarded on a 5-coin bet).\n2. Deal & Hold: Press Deal (Space). Click cards or press 1–5 to toggle HOLD on cards you wish to keep.\n3. Draw: Press Draw (Space). Unheld cards are replaced. Winnings are paid according to the pay table.\n\nGame Variants:\n• Jacks or Better: Standard pay table. Minimum qualifying hand is a pair of Jacks, Queens, Kings, or Aces (1×).\n• Deuces Wild: All four 2s are wild cards. Minimum winning hand is Three of a Kind. Special payouts for Four Deuces (200×) and Wild Royal Flush (25×).\n• Bonus Poker: Enhanced payouts for Four of a Kind (Four Aces pays 80×; Four 2s/3s/4s pays 40×).",
        .helpVideopokerStrategy: "1. Always Bet Max (5 Coins): The Royal Flush payout jumps from 250× to 800× only at 5 coins.\n2. Never Break a Made Hand (Except for 4-to-a-Royal): Only break a Straight or Flush if you are 1 card away from a Royal Flush.\n3. In Deuces Wild, Never Discard a 2: Deuces are wild—always hold every 2 dealt to you!",
        .helpVideopokerNoStress: "Enabling No Stress Mode in Options switches the game into Free Play—hiding bets, credits, and pay tables so you can play risk-free without wagers.",
        .helpBlackjackObjective: "Outscore the dealer's hand total without exceeding 21. Face cards = 10, Aces = 1 or 11, Number cards = face value.",
        .helpBlackjackRules: "1. Place Bet & Deal: Select your chip wager (1, 5, 10, 25) or press Bet Max (M), then press Deal (Space).\n2. Your Turn:\n  – Hit (H): Take another card.\n  – Stand (S): Keep your current hand.\n  – Double Down (D): Double your wager, receive exactly 1 card, and automatically stand. (Available on initial 2 cards with totals of 9, 10, or 11).\n  – Split (P): If dealt two matching ranks, split them into two separate hands (requires an equal second wager).\n3. Dealer's Turn: Dealer reveals their hidden card and must hit until reaching 17 or higher (stands on all 17s).\n\nPayout Schedule:\n• Standard Win: 1:1 payout.\n• Natural Blackjack (Ace + 10-value card): 3:1 payout.\n• Push (Tie): Bet is returned.",
        .helpBlackjackStrategy: "1. Always Split Aces and 8s: Never split 10s or 5s.\n2. Double Down on 11: Always Double Down when your starting hand totals 11 against a dealer 2 through 10.\n3. Watch the Dealer's Upcard: If the dealer shows a 2 through 6, they have a high chance of busting—stand on hard 12 or higher and let the dealer draw.",
        .helpBlackjackNoStress: "Enabling No Stress Mode in Options switches the game into Free Play—hiding bets and credits so you can play risk-free without wagers.",
        .helpHoneycombObjective: "Battle an AI opponent on a 3×3 grid using a 5-card deck. Each card features 4 directional stats (Top, Right, Bottom, Left). Place cards strategically to flip enemy cards to your color. Whoever controls the majority of the 9 grid cells at the end wins!",
        .helpHoneycombMechanics: "• Capturing: When you place a card adjacent to an opponent's card, your facing stat is compared against their opposite facing stat. If your stat is higher, the enemy card is captured (flipped to your color). Stat 10 is rendered as \"A\".\n• Hive Minds: A card captured during a turn immediately checks its own adjacent neighbors, triggering a chain-reaction capture sequence!",
        .helpHoneycombCardBank: "• Steal Mechanics: After winning a match, double-click an eligible dealer card to permanently steal it into your Card Bank! Only one steal is allowed per match.\n• Deck Rarity Caps: Custom decks are limited to: at most one 5★ card, and at most one 4★ card if a 5★ is present (or up to two 4★ cards without a 5★).\n• Smart Opponent Decks: The AI automatically selects decks containing cards you don't yet own to maximize steal rewards.\n• Steal Protection: Stuck in a Rematch chain against an opponent whose cards you just can't seem to capture? Win two Rematches in a row against the same opponent with nothing eligible to steal, and any not-yet-unlocked card left on the board becomes stealable on that second win — captured or not. Once triggered, it stays active for the rest of that Rematch chain, so every future win keeps offering a steal — you won't have to re-earn it. Starting a fresh New Game (a new opponent) is what turns it back off.",
        .helpHoneycombNoStress: "Enabling No Stress Mode in Options supplies you with a fixed strong deck every match and hides the Card Steal mechanics.",
        .helpCustomizationThemes: "• Felt Table: Choose from 5 preset felt colors (Green, Crimson, Royal Blue, Charcoal, Desert) or set a Custom Color via picker. Toggle edge vignette on/off.\n• Card Backs: Select built-in designs or upload custom .jpg/.png/.gif files.\n• Face Card Art: Upload custom image/GIF artwork individually for Aces, Jacks, Queens, and Kings.\n• Saved Themes: Snapshot your custom felt, card backs, and face art into named custom themes to apply anytime in one click!",
        .helpCustomizationOptions: "• Honey Mode (Flavor): Global toggle across all 6 games — controls the \"+N\"/\"-N\" score popups and whether flavor/ambiance banners appear. Turn it off for a quieter, more minimal play experience.\n• Stay on Top: Keeps the game window pinned above your other windows (View menu).\n• Sound Effects, Vegas Scoring, and Hide Hint Button are also available here per-game.",
        .helpKlondikeTitle: "Klondike Solitaire",
        .helpKlondikeSubtitle: "Classic single-deck solitaire with Draw 1, Draw 3, and Vegas scoring options.",
        .helpBeecellSubtitle: "The ultimate strategic solitaire game—99.9% of all deals are solvable.",
        .helpSpiderTitle: "Spider Solitaire",
        .helpSpiderSubtitle: "A deep, two-deck game of sequence building across 1, 2, or 4 suits.",
        .helpVideopokerTitle: "Video Poker",
        .helpVideopokerSubtitle: "Classic casino poker with Jacks or Better, Deuces Wild, and Bonus Poker pay tables.",
        .helpBlackjackTitle: "Video Blackjack",
        .helpBlackjackSubtitle: "Beat the dealer by getting closer to 21 without going over.",
        .helpThemesTitle: "Themes & Global Settings",
        .helpThemesSubtitle: "Customize the look of every game and adjust global modes.",
        .helpSetupLayoutTitle: "🃏 Setup & Layout",
        .helpRulesHowToPlayTitle: "🎮 Rules & How to Play",
        .helpRulesOptionsTitle: "🎮 Rules & Options",
        .helpMatchModifiersTitle: "🎲 Match Modifiers & Special Rules",
        .helpCardBankStealingTitle: "🏆 Card Bank & Stealing",
        .helpThemesCustomizationTitle: "🎨 Themes & Customization",
        .helpOptionsTitle: "⚙️ Options",
        .helpShortcutNavigateBoardCursor: "Navigate Board Cursor",
        .helpShortcutClearSelection: "Clear Selection",
        .helpShortcutDrawCards: "Draw Card(s)",
        .helpShortcutAutoMoveFoundation: "Auto-Move to Foundation",
        .helpShortcutNewGameRestartDeal: "New Game / Restart Deal",
        .helpShortcutUndoMove: "Undo Move",
        .helpShortcutToggleDraw: "Toggle Draw 1 / Draw 3",
        .helpShortcutCycleHints: "Cycle Available Hints",
        .helpShortcutHintButton: "Hint button",
        .helpShortcutAutoParkFreeCell: "Auto-Park to Free Cell",
        .helpShortcutArrowSpaceEnter: "Arrow Keys + Space / Enter",
        .helpShortcutDeal10Cards: "Deal 10 Cards from Stock",
        .helpShortcut1suit2suitMode: "1-Suit / 2-Suit Mode",
        .helpShortcutAutocomplete: "Autocomplete",
        .helpShortcutDealDraw: "Deal / Draw",
        .helpShortcutHoldCard12345: "Hold Card 1, 2, 3, 4, 5",
        .helpShortcut12345: "1, 2, 3, 4, 5",
        .helpShortcutHoldAllCards: "Hold All Cards",
        .helpShortcutBetMaxDeal: "Bet Max & Deal",
        .helpShortcutDealBuyIn: "Deal / Buy In",
        .helpShortcutHit: "Hit",
        .helpShortcutStand: "Stand",
        .helpShortcutDoubleDown: "Double Down",
        .ruleNamePollination: "Pollination",
        .ruleNameSmokedOut: "Smoked Out",
        .ruleNameSymmetry: "Symmetry",
        .ruleNameMathBee: "Math Bee",
        .ruleNameQueensFall: "Queen's Fall",
        .ruleNameInversion: "Inversion",
        .ruleNameClearSkies: "Clear Skies",
        .ruleNameHierarchy: "Hierarchy",
        .ruleNameFrenzy: "Frenzy",
        .ruleExplanationSame: "If 2+ touching neighbor stats match your card's facing stats, all matching neighbors are captured simultaneously.",
        .ruleExplanationPlus: "If the sum of (your stat + neighbor's stat) equals the same total across 2+ neighbors, all involved cards are captured.",
        .ruleExplanationFallenAce: "A card with a stat of 1 attacking a 10 (\"A\") always captures it! If Inversion is also active, this flips: a 10 (\"A\") captures a 1 instead.",
        .ruleExplanationAscensionGeneric: "Grants +1 to stats for all cards matching randomly selected suits as more of that suit enter the board.",
        .ruleExplanationDescensionGeneric: "Inflicts -1 to stats for all cards matching randomly selected suits as more of that suit enter the board.",
        .ruleExplanationOrder: "Forces you to play cards in exact deck sequence.",
        .ruleExplanationAllOpen: "Both players' hands are completely visible.",
        .ruleExplanationThreeOpen: "Three randomly selected cards from each player's hand are visible.",
        .ruleExplanationBombShelter: "Each player's first card played remains face-down for 3 turns before flipping automatically.",
        .ruleExplanationSuddenDeath: "If the match ends in a draw, a rematch begins immediately.",
        .ruleExplanationSwap: "Before the match, one card from your hand is randomly swapped with one of the opponent's.",
        .difficultyEasyRawvalue: "Easy",
        .difficultyMediumRawvalue: "Medium",
        .difficultyHardRawvalue: "Hard",
        .gamemodeBeecellDisplay: "Beecell",
        .rouletteColonPrefix: "Roulette: ",
        .rulesRandomizedAtStart: "Rules are randomized at the start of the match.",
        .ruleNameColonFmt: "%@: ",
        .matchRulesHintWin: "Pick up to 4 rules to lock in, or leave empty to let roulette decide. Ban a rule to keep it out entirely. Hover over a rule to see its explanation.",
        .opponentLabelColon: "Opponent:",
        .saveNewThemeEllipsisWin: "Save New Theme…",
        .firstMovePlayer: "First Move: Player!",
        .firstMoveOpponentFmt: "First Move: %@!",
        .helpNoStressModeTitle: "🧘 No Stress Mode",
        .helpGuideContentsHeader: "CONTENTS",
        .helpGuideWindowTitle: "Help Guide",
        .helpThemesSettingsIndexLabel: "Themes & Settings",
        .helpShortcutClearAllHolds: "Clear All Holds",
        .settingsHeaderVideopoker: "VIDEO POKER",
        .handRoyalFlush: "Royal Flush",
        .handJacksOrBetter: "Jacks or Better",
        .swarmRevealPlayerHiveSwarm: "Your Hive Swarm",
        .swarmRevealPlayerUnleashed: "Your Swarm is Unleashed!",
        .swarmRevealPlayerAwakens: "Your Swarm Awakens!",
        .swarmRevealPlayerBuzzing: "Your Hive is Buzzing into Action!",
        .swarmRevealOpponentHiveSwarmFmt: "%@'s Hive Swarm",
        .swarmRevealOpponentUnleashedFmt: "%@'s Swarm is Unleashed!",
        .swarmRevealOpponentAwakensFmt: "%@'s Swarm Awakens!",
        .swarmRevealOpponentBuzzingFmt: "%@'s Hive is Buzzing into Action!",
        .bannerHiveMindFmt: "HIVE MIND x%d!",
        .gameModeSectionHeader: "Game Mode",
        .savedThemesHeader: "Saved Themes",
        .doubleClickCardOrBackgroundTooltip: "Double-click the card or the background to adjust it",
        .deleteBackgroundConfirmBody: "Are you sure you want to delete this custom background? This cannot be undone.",
        .saveNewThemeTitle: "Save New Theme",
        .enterThemeNamePrompt: "Enter a name for this theme:",
        .tapTileUploadArtHint: "Tap a tile to upload art. Tap again to adjust.",
        .suitNameSpadesPlain: "Spades",
        .suitNameHeartsPlain: "Hearts",
        .suitNameDiamondsPlain: "Diamonds",
        .suitNameClubsPlain: "Clubs",
        .aboutDownloadingUpdate: "Downloading update…",
        .aboutDownloadingUpdatePctFmt: "Downloading update… %d%%",
        .aboutUpdateDownloadFailed: "Failed to download the update.",
        .installAndRestart: "Install & Restart",
        .addBackgroundTitle: "Add Background",
        .editBackgroundTitle: "Edit Background",
        .cardBackFillNote: "This card back fills the card automatically\nand doesn't use position adjustments.",
        .btnDealDHotkey: "Deal  [D]",
        .btnDrawDHotkey: "Draw  [D]",
        .removeFromDeckContextMenu: "Remove from deck?",
        .starCountFilterFmt: "%d Star%@",
        .noCardsMatchFilter: "No cards match this filter.",
        .youLose: "You Lose",
        .drawSuddenDeathFmt: "Draw - %@!",
        .resultDealerWins: "Dealer Wins",
        .resultHandWinFmt: "Hand %d: Win",
        .resultHandLossFmt: "Hand %d: Loss",
        .resultHandPushFmt: "Hand %d: Push",
        .resultHandBustFmt: "Hand %d: Bust",
        .newMatchConfirmTitle: "Start a new match? Your current match will end.",
        .rematchConfirmTitle: "Rematch? Your current match will end.",
        .menuTabGameSelection: "Game Selection",
        .menuHeaderTitle: "Menu",
        .closeMenuA11y: "Close menu",
        .menuSectionGame: "Game",
        .menuSectionTheme: "Theme",
        .menuSectionCardBack: "Card Back",
        .menuSectionBackground: "Background",
        .backgroundNoneOption: "None",
        .removeCardBackAlertTitle: "Remove Card Back?",
        .removeBackgroundAlertTitle: "Remove Background?",
        .removeFaceArtAlertTitle: "Remove Face Art?",
        .removeImportedImageBody: "This removes the imported image. It can't be undone.",
        .statisticsNavRow: "Statistics",
        .howToPlayNavRow: "How to Play",
        .faceCardArtNavRow: "Face Card Art",
        .touchNewDealLabel: "New",
        .touchUndoLastMoveLabel: "Undo Last Move",
        .touchDealA11y: "Deal",
        .touchCompletedRunsA11y: "Completed runs",
        .touchDecksPickerLabel: "Decks",
        .touchSingleDeckOption: "Single Deck",
        .touchDoubleDeckOption: "Double Deck",
        .touchSuitsPickerLabel: "Suits",
        .touchBetMaxButton: "Max",
        .touchSettingsUnlockBetweenHands: "Settings unlock between hands.",
        .touchSettingsUnlockHandEnds: "Settings unlock when the hand ends.",
        .touchHandsDealtStat: "Hands Dealt",
        .touchSessionCreditsStat: "Session Credits",
        .touchHandLabelFmt: "HAND %d",
        .touchYouLabel: "YOU",
        .touchBustSuffix: " BUST",
        .touchResultWin: "WIN",
        .touchResultLoss: "LOSS",
        .touchResultPush: "PUSH",
        .touchResultBlackjack: "BLACKJACK!",
        .touchResultBust: "BUST",
        .touchActionHit: "Hit",
        .touchActionStand: "Stand",
        .touchActionDouble: "Double",
        .touchActionSplit: "Split",
        .touchResetPositionButton: "Reset Position",
        .touchAddCardBackTitle: "Add Card Back",
        .stealInstructionTap: "Double-tap a captured opponent's card\non the board to steal it.",
        .touchLayoutComingSoon: "Touch layout coming soon",
        .touchBlackjackTitle: "Blackjack",
        .touchBlackjackBanner: "BLACKJACK",
        .touchSpiderBanner: "SPIDER",
        .touchKlondikeBanner: "KLONDIKE",
        .touchBeecellBanner: "BEECELL",
        .debugBannersMenu: "Banners",
        .deckDefaultName: "Default",
        .freePlayLabel: "Free Play",
        .touchChoosePhoto: "Choose Photo",
        .touchChooseDifferentPhoto: "Choose a Different Photo",
        .touchPinchZoomReposition: "Pinch to zoom, drag to reposition",
        .touchNameFieldPlaceholder: "Name",
        .touchNameAlreadyTakenError: "That name is already taken — pick another.",
        .touchEnabledToggle: "Enabled",
        .cardBackDefaultName: "Default",
        .addPhotoShort: "Add Photo",
        .feltCustomShort: "Custom Felt",
        .statPositionTop: "Top",
        .statPositionBottom: "Bottom",
        .statPositionLeft: "Left",
        .statPositionRight: "Right",
        .statFilterAny: "Any",
        .statSuddenDeathCountIos: "Sudden Deaths",
        .statFallenAcesIos: "Fallen Aces",
        .ruleStateAuto: "Auto",
        .ruleStatePick: "Play",
        .ruleStateBan: "Ban",
        .rulesSelectedCountFmt: "%d of 4 selected",
        .outOfCreditsToast: "Out of Credits!",
        .btnClearShort: "Clear",
        .globalOptionsSection: "Global",
    ]
}
