using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json.Nodes;
using Xunit;
using SoliBee.Core.Models;

namespace SoliBee.Tests.Core;

// Cross-platform parity for the Honeycomb card database against Mac's
// (shared/Honeycomb/TestVectors/honeycomb_card_database_vectors.json, generated by
// mac/SoliBeeTests/HoneycombCardDatabaseVectorTests.swift). Checks the parts that must
// match: the same ids, names, star tiers and suits in the same order, and every card's
// stats obeying its tier's rules (per-edge range, total budget, no duplicate stat line
// within a suit). Exact stat values per seed are NOT compared: each platform's seeded
// RNG helpers (weighted pick / shuffle) consume the stream differently, so the same seed
// yields different — but identically distributed — stats. Seeds are per-install and
// never shared across platforms, and forcing identical output would reroll every
// existing player's collection, so that difference is intentional.
public class HoneycombCardDatabaseVectorTests
{
    private static string VectorsPath()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            var f = Path.Combine(dir.FullName, "shared", "Honeycomb", "TestVectors", "honeycomb_card_database_vectors.json");
            if (File.Exists(f)) return f;
            dir = dir.Parent;
        }
        throw new FileNotFoundException("honeycomb_card_database_vectors.json not found");
    }

    [Fact]
    public void GeneratorMatchesMacForEverySeed()
    {
        var dbs = JsonNode.Parse(File.ReadAllText(VectorsPath()))!["databases"]!.AsArray();
        Assert.NotEmpty(dbs);
        var failures = new List<string>();
        foreach (var db in dbs)
        {
            var seedText = db!["seed"]!.GetValue<string>();
            var expected = db["cards"]!.AsArray().Select(n => n!.AsArray()).ToList();
            var cards = HoneycombCardGenerator.GenerateAllCards(ulong.Parse(seedText));
            var expectedIdentity = expected.Select(a => $"{a[0]}|{a[1]}|{a[2]}|{a[4]}");
            var actualIdentity = cards.Select(c => $"{c.Id}|{c.Name}|{c.Stars}|{c.Suit}");
            if (!expectedIdentity.SequenceEqual(actualIdentity))
                failures.Add($"seed {seedText}: card ids/names/stars/suits differ from Mac");
            // Per-tier rules, taken from Mac's generated cards: per-edge range and budget.
            var rules = expected.GroupBy(a => a[2]!.GetValue<int>()).ToDictionary(g => g.Key, g =>
            {
                var edges = g.SelectMany(a => a[3]!.AsArray().Select(x => x!.GetValue<int>())).ToList();
                var sums = g.Select(a => a[3]!.AsArray().Sum(x => x!.GetValue<int>())).ToList();
                return (MinE: edges.Min(), MaxE: edges.Max(), MinS: sums.Min(), MaxS: sums.Max());
            });
            foreach (var c in cards)
            {
                var r = rules[c.Stars];
                int sum = c.Stats.Sum();
                if (c.Stats.Any(v => v < r.MinE || v > r.MaxE) || sum < r.MinS || sum > r.MaxS)
                    failures.Add($"seed {seedText}: {c.Name} ({c.Stars}★) stats [{string.Join(",", c.Stats)}] outside Mac's range {r.MinE}-{r.MaxE} / budget {r.MinS}-{r.MaxS}");
            }
            foreach (var g in cards.GroupBy(c => c.Suit))
                if (g.Select(c => string.Join(",", c.Stats)).Distinct().Count() != g.Count())
                    failures.Add($"seed {seedText}: duplicate stat line in suit {g.Key}");
        }
        Assert.True(failures.Count == 0, "Card database diverges from Mac:\n" + string.Join("\n", failures));
    }
}
