import Foundation

/// Debug-only grouping of BannerCatalog's full flavor-text catalog (BannerID.swift,
/// generated from tools/Honeycomb_Localization.xlsx's BannerFlavorText sheet) for the
/// debug menu — distinct from DebugBannerKind (win/loss/same/plus/suddenDeath), which
/// only covers match-result overlays and rule-combo banners. Shared by mac's native
/// DebugBannerCommands and iOS's in-app debug menu icon so both list the exact same
/// triggers, fired via BannerCatalog.debugPreviewText(for:)/
/// HoneycombViewModel.debugFireCatalogBanner(_:). Hand-maintained (not regenerated by
/// generate_banner_catalog.py) — debug-only, will be removed before TestFlight, so it
/// wasn't worth wiring into that pipeline. Labels are the spreadsheet's own Trigger text.
public enum DebugBannerCatalogMenu {
    public static let sections: [(title: String, items: [(label: String, id: BannerID)])] = [
        ("Rule-Specific", [
            ("Nectar Exchange swaps away the player's 5-star card.", .ruleSpecificNectarExchangeSwapsAwayThePlayers5StarCard),
            ("Nectar Exchange trades the player's worst card for the opponent's best.", .ruleSpecificNectarExchangeTradesThePlayersWorstCardForThe),
            ("Roulette rolls zero extra rules.", .ruleSpecificRouletteRollsZeroExtraRules),
            ("Fallen Ace triggers (a '1' captures a '10').", .ruleSpecificFallenAceTriggersA1CapturesA10),
            ("Pollination pushes a card's modifier to +3 or higher.", .ruleSpecificPollinationPushesACardsModifierTo3OrHigher),
            ("Smoked Out drops a card's effective stat to 1.", .ruleSpecificSmokedOutDropsACardsEffectiveStatTo1),
            ("A player triggers a \"Plus\" combo (the math matches perfectly).", .ruleSpecificAPlayerTriggersAPlusComboTheMathMatchesPerfectly),
            ("Player wins flawless (opponent score = 0).", .ruleSpecificPlayerWinsFlawlessOpponentScore0),
            ("Player loses flawless (0 captures).", .ruleSpecificPlayerLosesFlawless0Captures),
            ("Roulette rolls Pollination.", .ruleSpecificRouletteRollsPollination),
            ("Roulette rolls Smoked Out.", .ruleSpecificRouletteRollsSmokedOut),
            ("Roulette rolls Math Bee", .ruleSpecificRouletteRollsMathBee),
            ("Roulette rolls Inversion", .ruleSpecificRouletteRollsInversion),
            ("Roulette rolls clear skies", .ruleSpecificRouletteRollsClearSkies),
            ("Roulette rolls scouting party", .ruleSpecificRouletteRollsScoutingParty),
            ("Roulette rolls Frenzy", .ruleSpecificRouletteRollsFrenzy),
            ("Roulette rolls Symmetry", .ruleSpecificRouletteRollsSymmetry),
            ("Roulette rolls Nectar Exchange", .ruleSpecificRouletteRollsNectarExchange),
            ("Roulette rolls Hierarchy", .ruleSpecificRouletteRollsHierarchy),
        ]),
        ("Loading", [
            ("Game loads on May 20th (World Bee Day).", .loadingGameLoadsOnMay20thWorldBeeDay),
            ("Game loads on New Year's Day (Jan 1).", .loadingGameLoadsOnNewYearsDayJan1),
            ("Game loads on Halloween (Oct 31).", .loadingGameLoadsOnHalloweenOct31),
            ("Game loads on Valentine's Day (Feb 14).", .loadingGameLoadsOnValentinesDayFeb14),
            ("First launch after playing for one year.", .loadingFirstLaunchAfterPlayingForOneYear),
            ("Playing on April Fools' Day (Apr 1).", .loadingPlayingOnAprilFoolsDayApr1),
            ("Match starts between 12:00 AM and 5:00 AM local time.", .loadingMatchStartsBetween1200AmAnd500AmLocalTime),
            ("Match starts between 5:00 AM and 8:00 AM local time.", .loadingMatchStartsBetween500AmAnd800AmLocalTime),
            ("Match starts between 9:00 PM and midnight local time.", .loadingMatchStartsBetween900PmAndMidnightLocalTime),
            ("Match starts within a minute of local noon.", .loadingMatchStartsWithinAMinuteOfLocalNoon),
            ("Match starts between 8:00 AM and 12:00 PM local time.", .loadingMatchStartsBetween800AmAnd1200PmLocalTime),
            ("Match starts between 12:00 PM and 2:00 PM local time.", .loadingMatchStartsBetween1200PmAnd200PmLocalTime),
            ("Match starts between 2:00 PM and 5:00 PM local time.", .loadingMatchStartsBetween200PmAnd500PmLocalTime),
            ("Match starts between 5:00 PM and 9:00 PM local time.", .loadingMatchStartsBetween500PmAnd900PmLocalTime),
            ("On Game Load", .loadingOnGameLoad),
            ("Game loads on Earth Day (Apr 22).", .loadingGameLoadsOnEarthDayApr22),
            ("Game loads on National Honey Day (Aug 15).", .loadingGameLoadsOnNationalHoneyDayAug15),
            ("Game loads on Pi Day (Mar 14).", .loadingGameLoadsOnPiDayMar14),
            ("Game loads on New Year's Eve (Dec 31).", .loadingGameLoadsOnNewYearsEveDec31),
            ("Game loads on Christmas (Dec 25).", .loadingGameLoadsOnChristmasDec25),
            ("Game loads on Holi.", .loadingGameLoadsOnHoli),
            ("Game loads on Rosh Hashanah.", .loadingGameLoadsOnRoshHashanah),
            ("Game loads on Diwali.", .loadingGameLoadsOnDiwali),
            ("Game loads on Eid al-Fitr.", .loadingGameLoadsOnEidAlFitr),
            ("Game loads on Hanukkah.", .loadingGameLoadsOnHanukkah),
        ]),
        ("Idle Action", [
            ("No action taken for one minute.", .idleActionNoActionTakenForOneMinute),
        ]),
        ("Gameplay", [
            ("3+ Hints used in one match.", .gameplay3HintsUsedInOneMatch),
            ("Undo used immediately after a placement.", .gameplayUndoUsedImmediatelyAfterAPlacement),
            ("Player wins a match with 4 rules active at once.", .gameplayPlayerWinsAMatchWith4RulesActiveAtOnce),
            ("Opponent is winning by two cards and is about to place the last card on the board.", .gameplayOpponentIsWinningByTwoCardsAndIsAboutToPlaceThe),
            ("Player flips 3+ cards in a single turn.", .gameplayPlayerFlips3CardsInASingleTurn),
            ("Opponent flips 3+ of the player's cards in a single turn (not a Combo).", .gameplayOpponentFlips3OfThePlayersCardsInASingleTurnNotA),
            ("Combo x4 or higher.", .gameplayComboX4OrHigher),
            ("Player has only 2 cards on the board vs. opponent's 6, few spaces left.", .gameplayPlayerHasOnly2CardsOnTheBoardVsOpponents6Few),
            ("A placed card captures on all 4 sides at once.", .gameplayAPlacedCardCapturesOnAll4SidesAtOnce),
            ("3+ rematch wins in a row against the same opponent.", .gameplay3RematchWinsInARowAgainstTheSameOpponent),
            ("3+ rematch losses in a row against the same opponent.", .gameplay3RematchLossesInARowAgainstTheSameOpponent),
            ("A 1-star card captures 3+ cards in one move.", .gameplayA1StarCardCaptures3CardsInOneMove),
            ("A 1-star card captures a 5-star card (rarity mismatch).", .gameplayA1StarCardCapturesA5StarCardRarityMismatch),
            ("Player uses Undo, thinks about it, and then makes the exact same move they just undid.", .gameplayPlayerUsesUndoThinksAboutItAndThenMakesTheExact),
            ("Player plays against the same AI difficulty 5 times in a row.", .gameplayPlayerPlaysAgainstTheSameAiDifficulty5TimesInARow),
            ("Player wins by the maximum possible margin.", .gameplayPlayerWinsByTheMaximumPossibleMargin),
        ]),
        ("Milestones", [
            ("First launch ever", .milestonesFirstLaunchEver),
            ("Player reaches 10 total wins.", .milestonesPlayerReaches10TotalWins),
            ("Player reaches 100 total wins.", .milestonesPlayerReaches100TotalWins),
            ("Player reaches 1000 total wins.", .milestonesPlayerReaches1000TotalWins),
        ]),
    ]
}
