package com.leah.honeycomb.honeycomb

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

// Cross-platform parity for the Honeycomb card database against Mac's
// (shared/Honeycomb/TestVectors/honeycomb_card_database_vectors.json, generated by
// mac/SoliBeeTests/HoneycombCardDatabaseVectorTests.swift). Checks the parts that must
// match: the same ids, names, star tiers and suits in the same order, and every card's
// stats obeying its tier's rules (per-edge range, total budget, no duplicate stat line
// within a suit). Exact stat values per seed are NOT compared: each platform's seeded
// RNG helpers (weighted pick / shuffle) consume the stream differently, so the same seed
// yields different — but identically distributed — stats. Seeds are per-install and
// never shared across platforms, and forcing identical output would reroll every
// existing player's collection, so that difference is intentional.
class HoneycombCardDatabaseVectorTests {
    private fun vectorsFile(): File {
        var dir: File? = File("").absoluteFile
        while (dir != null) {
            val f = File(dir, "shared/Honeycomb/TestVectors/honeycomb_card_database_vectors.json")
            if (f.exists()) return f
            dir = dir.parentFile
        }
        error("honeycomb_card_database_vectors.json not found")
    }

    @Test
    fun generatorMatchesMacForEverySeed() {
        val dbs = Json.parseToJsonElement(vectorsFile().readText()).jsonObject["databases"]!!.jsonArray
        if (dbs.isEmpty()) fail("no card database vectors loaded")
        val failures = mutableListOf<String>()
        for (db in dbs) {
            val seedText = db.jsonObject["seed"]!!.jsonPrimitive.content
            val expected = db.jsonObject["cards"]!!.jsonArray.map { c ->
                val a = c.jsonArray
                listOf(a[0].jsonPrimitive.int, a[1].jsonPrimitive.content, a[2].jsonPrimitive.int,
                    a[3].jsonArray.map { it.jsonPrimitive.int }, a[4].jsonPrimitive.content)
            }
            val cards = HoneycombCardGenerator.generateAllCards(seedText.toULong().toLong())
            val actualIdentity = cards.map { listOf(it.id, it.name, it.stars, it.suit) }
            val expectedIdentity = expected.map { listOf(it[0], it[1], it[2], it[4]) }
            if (expectedIdentity != actualIdentity) failures += "seed $seedText: card ids/names/stars/suits differ from Mac"
            // Per-tier rules, taken from Mac's generated cards: per-edge range and budget.
            val rangeByStars = expected.groupBy { it[2] as Int }.mapValues { (_, cs) ->
                val all = cs.flatMap { it[3] as List<*> }.map { it as Int }
                val sums = cs.map { (it[3] as List<*>).sumOf { v -> v as Int } }
                Pair(all.min()..all.max(), sums.min()..sums.max())
            }
            for (c in cards) {
                val (edge, budget) = rangeByStars.getValue(c.stars)
                if (c.stats.any { it !in edge } || c.stats.sum() !in budget) {
                    failures += "seed $seedText: ${c.name} (${c.stars}★) stats ${c.stats} outside Mac's range $edge / budget $budget"
                }
            }
            cards.groupBy { it.suit }.forEach { (suit, cs) ->
                if (cs.map { it.stats }.toSet().size != cs.size) failures += "seed $seedText: duplicate stat line in suit $suit"
            }
        }
        if (failures.isNotEmpty()) fail("Card database diverges from Mac:\n" + failures.joinToString("\n"))
    }
}
